import type { Lang } from './i18n'

/**
 * The words of the accounts flow, the catalogue and the profile — merged into
 * MESSAGES in i18n.ts. Kept apart from the older table only so the three
 * languages of each screen sit side by side.
 *
 * Field placeholders say what to do ("Enter your name"), never show a sample
 * value: a sample reads as already filled in.
 */
export const APP_COPY: Record<Lang, Record<string, string>> = {
  az: {
    'welcome.lead': 'Təzə balıq, pendir və dəniz məhsulları — qapınıza qədər.',
    'welcome.back': 'Yenidən xoş gördük, {name}',
    'welcome.backLead': 'Davam etmək üçün parolunuzu daxil edin.',
    'welcome.notYou': 'Siz deyilsiniz?',
    'tab.signIn': 'Daxil ol',
    'tab.signUp': 'Qeydiyyat',

    'f.name': 'Ad və soyad',
    'ph.name': 'Adınızı və soyadınızı daxil edin',
    'f.email': 'E-poçt',
    'ph.email': 'E-poçt ünvanınızı daxil edin',
    'f.dob': 'Doğum tarixi',
    'ph.dob': 'Doğum tarixinizi seçin',
    'f.password': 'Parol',
    'ph.password': 'Parol yaradın',
    'ph.passwordLogin': 'Parolunuzu daxil edin',
    'f.password2': 'Parolu təkrarlayın',
    'ph.password2': 'Parolu yenidən daxil edin',
    'ph.newPassword': 'Yeni parol yaradın',
    'pw.show': 'Parolu göstər',
    'pw.hide': 'Parolu gizlət',
    'pw.len': 'Ən azı 8 simvol',
    'pw.upper': 'Böyük hərf',
    'pw.lower': 'Kiçik hərf',
    'pw.digit': 'Rəqəm',
    'pw.symbol': 'Simvol (!@#…)',

    'err.name': 'Adınızı və soyadınızı yazın.',
    'err.email': 'Düzgün e-poçt ünvanı daxil edin.',
    'err.dob': 'Doğum tarixinizi seçin.',
    'err.age': 'Hesab açmaq üçün ən azı 13 yaşınız olmalıdır.',
    'err.password': 'Parol bütün tələblərə cavab verməlidir.',
    'err.match': 'Parollar eyni deyil.',
    'err.login': 'E-poçt və ya parol yanlışdır.',
    'err.tooMany': 'Çox cəhd oldu. Bir az gözləyib yenidən yoxlayın.',

    'signUp.cta': 'Qeydiyyatdan keç',
    'signIn.cta': 'Daxil ol',
    'forgot': 'Parolu unutmusunuz?',
    'or': 'və ya',
    'google': 'Google ilə davam et',
    'apple': 'Apple ilə davam et',
    'social.off': 'Bu giriş üsulu tezliklə aktiv olacaq.',
    'terms': 'Davam etməklə {policy} ilə razılaşırsınız.',
    'terms.policy': 'Məxfilik siyasəti',

    'dob.title': 'Doğum tarixi',
    'dob.day': 'Gün',
    'dob.month': 'Ay',
    'dob.year': 'İl',
    'dob.done': 'Seç',
    'months': 'Yanvar,Fevral,Mart,Aprel,May,İyun,İyul,Avqust,Sentyabr,Oktyabr,Noyabr,Dekabr',

    'otp.title': 'E-poçtunuzu təsdiqləyin',
    'otp.lead': '6 rəqəmli kodu bu ünvana göndərdik:',
    'otp.resendIn': 'Yeni kod {s} saniyədən sonra',
    'otp.resend': 'Kodu yenidən göndər',
    'otp.resent': 'Yeni kod göndərildi.',
    'otp.wrong': 'Kod düzgün deyil. Yenidən yoxlayın.',
    'otp.spam': 'Məktub gəlməyibsə, «Spam» qovluğuna baxın.',
    'otp.change': 'E-poçtu dəyiş',
    'otp.verify': 'Təsdiqlə',
    'otp.done': 'Hesabınız hazırdır',

    'forgot.title': 'Yeni parol',
    'forgot.lead': 'E-poçtunuzu və yeni parolu yazın — təsdiq üçün kod göndərəcəyik.',
    'forgot.cta': 'Kodu göndər',

    'cat.title': 'Kataloq',
    'cat.search': 'Məhsul axtarın',
    'cat.popular': 'Hit məhsullar',
    'cat.popularLead': 'Ən çox sifariş olunanlar',
    'cat.all': 'Bütün məhsullar',
    'cat.seeAll': 'Hamısı',
    'cat.count': '{n} məhsul',
    'cat.sort': 'Sıralama',
    'cat.sortPopular': 'Populyarlığa görə',
    'cat.sortCheap': 'Əvvəlcə ucuz',
    'cat.sortDear': 'Əvvəlcə baha',
    'cat.sortName': 'Ada görə',
    'cat.hit': 'Hit',
    'cat.banner': 'Bu gün sifariş edin — sabah qapınızda',
    'cat.bannerLead': 'Çatdırılma {open}–{close}, Bakı və ətrafı',
    'cat.greeting': 'Salam, {name}',

    'unit.kg': 'kq',
    'product.add': 'Səbətə əlavə et',
    'product.inBasket': 'Səbətdə',
    'product.about': 'Məhsul haqqında',
    'product.close': 'Bağla',

    'search.empty': 'Heç nə tapılmadı',
    'search.hint': 'Adı üç dildən birində yazın — «лосось» da, «salmon» da tapılır.',

    'profile.personal': 'Şəxsi məlumatlar',
    'profile.email': 'E-poçt',
    'profile.dob': 'Doğum tarixi',
    'profile.notSet': 'Əlavə edilməyib',
    'profile.edit': 'Redaktə et',
    'profile.settings': 'Tənzimləmələr',
    'profile.account': 'Hesab',
    'profile.signOutConfirm': 'Hesabdan çıxmaq istəyirsiniz?',
    'profile.deleteTitle': 'Hesab silinsin?',
    'profile.deleteHint': 'Sifarişləriniz yolda olarsa, əvvəlcə onlar tamamlanmalıdır.',
    'profile.deleted': 'Hesabınız silindi.',
    'profile.phonePh': 'Telefon nömrənizi daxil edin',
  },

  ru: {
    'welcome.lead': 'Свежая рыба, сыры и морепродукты — до вашей двери.',
    'welcome.back': 'С возвращением, {name}',
    'welcome.backLead': 'Введите пароль, чтобы продолжить.',
    'welcome.notYou': 'Это не вы?',
    'tab.signIn': 'Вход',
    'tab.signUp': 'Регистрация',

    'f.name': 'Имя и фамилия',
    'ph.name': 'Введите имя и фамилию',
    'f.email': 'Эл. почта',
    'ph.email': 'Введите адрес эл. почты',
    'f.dob': 'Дата рождения',
    'ph.dob': 'Выберите дату рождения',
    'f.password': 'Пароль',
    'ph.password': 'Придумайте пароль',
    'ph.passwordLogin': 'Введите пароль',
    'f.password2': 'Повторите пароль',
    'ph.password2': 'Введите пароль ещё раз',
    'ph.newPassword': 'Придумайте новый пароль',
    'pw.show': 'Показать пароль',
    'pw.hide': 'Скрыть пароль',
    'pw.len': 'Не меньше 8 символов',
    'pw.upper': 'Заглавная буква',
    'pw.lower': 'Строчная буква',
    'pw.digit': 'Цифра',
    'pw.symbol': 'Символ (!@#…)',

    'err.name': 'Укажите имя и фамилию.',
    'err.email': 'Введите правильный адрес эл. почты.',
    'err.dob': 'Выберите дату рождения.',
    'err.age': 'Чтобы открыть аккаунт, вам должно быть не меньше 13 лет.',
    'err.password': 'Пароль должен отвечать всем требованиям.',
    'err.match': 'Пароли не совпадают.',
    'err.login': 'Неверная эл. почта или пароль.',
    'err.tooMany': 'Слишком много попыток. Подождите немного и попробуйте снова.',

    'signUp.cta': 'Зарегистрироваться',
    'signIn.cta': 'Войти',
    'forgot': 'Забыли пароль?',
    'or': 'или',
    'google': 'Продолжить с Google',
    'apple': 'Продолжить с Apple',
    'social.off': 'Этот способ входа скоро заработает.',
    'terms': 'Продолжая, вы соглашаетесь с {policy}.',
    'terms.policy': 'Политикой конфиденциальности',

    'dob.title': 'Дата рождения',
    'dob.day': 'День',
    'dob.month': 'Месяц',
    'dob.year': 'Год',
    'dob.done': 'Выбрать',
    'months': 'Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь',

    'otp.title': 'Подтвердите почту',
    'otp.lead': 'Мы отправили 6-значный код на адрес:',
    'otp.resendIn': 'Новый код через {s} с',
    'otp.resend': 'Отправить код ещё раз',
    'otp.resent': 'Новый код отправлен.',
    'otp.wrong': 'Неверный код. Проверьте и попробуйте снова.',
    'otp.spam': 'Если письма нет, загляните в папку «Спам».',
    'otp.change': 'Изменить почту',
    'otp.verify': 'Подтвердить',
    'otp.done': 'Аккаунт готов',

    'forgot.title': 'Новый пароль',
    'forgot.lead': 'Укажите почту и новый пароль — мы отправим код для подтверждения.',
    'forgot.cta': 'Отправить код',

    'cat.title': 'Каталог',
    'cat.search': 'Поиск товаров',
    'cat.popular': 'Хиты',
    'cat.popularLead': 'Заказывают чаще всего',
    'cat.all': 'Все товары',
    'cat.seeAll': 'Все',
    'cat.count': 'Товаров: {n}',
    'cat.sort': 'Сортировка',
    'cat.sortPopular': 'По популярности',
    'cat.sortCheap': 'Сначала дешевле',
    'cat.sortDear': 'Сначала дороже',
    'cat.sortName': 'По названию',
    'cat.hit': 'Хит',
    'cat.banner': 'Закажите сегодня — завтра у вашей двери',
    'cat.bannerLead': 'Доставка {open}–{close}, Баку и пригороды',
    'cat.greeting': 'Здравствуйте, {name}',

    'unit.kg': 'кг',
    'product.add': 'В корзину',
    'product.inBasket': 'В корзине',
    'product.about': 'О товаре',
    'product.close': 'Закрыть',

    'search.empty': 'Ничего не найдено',
    'search.hint': 'Пишите на любом из трёх языков — найдётся и «лосось», и «salmon».',

    'profile.personal': 'Личные данные',
    'profile.email': 'Эл. почта',
    'profile.dob': 'Дата рождения',
    'profile.notSet': 'Не указано',
    'profile.edit': 'Изменить',
    'profile.settings': 'Настройки',
    'profile.account': 'Аккаунт',
    'profile.signOutConfirm': 'Выйти из аккаунта?',
    'profile.deleteTitle': 'Удалить аккаунт?',
    'profile.deleteHint': 'Если заказ в пути, сначала он должен быть доставлен или отменён.',
    'profile.deleted': 'Аккаунт удалён.',
    'profile.phonePh': 'Введите номер телефона',
  },

  en: {
    'welcome.lead': 'Fresh fish, cheese and seafood — to your door.',
    'welcome.back': 'Welcome back, {name}',
    'welcome.backLead': 'Enter your password to carry on.',
    'welcome.notYou': 'Not you?',
    'tab.signIn': 'Sign in',
    'tab.signUp': 'Sign up',

    'f.name': 'Name and surname',
    'ph.name': 'Enter your name and surname',
    'f.email': 'Email',
    'ph.email': 'Enter your email address',
    'f.dob': 'Date of birth',
    'ph.dob': 'Select your date of birth',
    'f.password': 'Password',
    'ph.password': 'Create a password',
    'ph.passwordLogin': 'Enter your password',
    'f.password2': 'Repeat password',
    'ph.password2': 'Enter your password again',
    'ph.newPassword': 'Create a new password',
    'pw.show': 'Show password',
    'pw.hide': 'Hide password',
    'pw.len': 'At least 8 characters',
    'pw.upper': 'An uppercase letter',
    'pw.lower': 'A lowercase letter',
    'pw.digit': 'A digit',
    'pw.symbol': 'A symbol (!@#…)',

    'err.name': 'Enter your name and surname.',
    'err.email': 'Enter a valid email address.',
    'err.dob': 'Select your date of birth.',
    'err.age': 'You must be at least 13 to open an account.',
    'err.password': 'The password has to meet every rule.',
    'err.match': 'The passwords do not match.',
    'err.login': 'The email or password is not right.',
    'err.tooMany': 'Too many tries. Wait a little and try again.',

    'signUp.cta': 'Create account',
    'signIn.cta': 'Sign in',
    'forgot': 'Forgot your password?',
    'or': 'or',
    'google': 'Continue with Google',
    'apple': 'Continue with Apple',
    'social.off': 'This way of signing in is coming soon.',
    'terms': 'By continuing you agree to the {policy}.',
    'terms.policy': 'Privacy policy',

    'dob.title': 'Date of birth',
    'dob.day': 'Day',
    'dob.month': 'Month',
    'dob.year': 'Year',
    'dob.done': 'Done',
    'months': 'January,February,March,April,May,June,July,August,September,October,November,December',

    'otp.title': 'Confirm your email',
    'otp.lead': 'We sent a 6-digit code to:',
    'otp.resendIn': 'New code in {s}s',
    'otp.resend': 'Send the code again',
    'otp.resent': 'A new code is on its way.',
    'otp.wrong': 'That code is not right. Check it and try again.',
    'otp.spam': 'No email? Have a look in your Spam folder.',
    'otp.change': 'Change email',
    'otp.verify': 'Confirm',
    'otp.done': 'Your account is ready',

    'forgot.title': 'New password',
    'forgot.lead': 'Enter your email and a new password — we will send a code to confirm it.',
    'forgot.cta': 'Send code',

    'cat.title': 'Catalogue',
    'cat.search': 'Search products',
    'cat.popular': 'Best sellers',
    'cat.popularLead': 'What people order most',
    'cat.all': 'All products',
    'cat.seeAll': 'See all',
    'cat.count': '{n} products',
    'cat.sort': 'Sort',
    'cat.sortPopular': 'By popularity',
    'cat.sortCheap': 'Price: low to high',
    'cat.sortDear': 'Price: high to low',
    'cat.sortName': 'By name',
    'cat.hit': 'Hit',
    'cat.banner': 'Order today — at your door tomorrow',
    'cat.bannerLead': 'Delivery {open}–{close}, Baku and around',
    'cat.greeting': 'Hello, {name}',

    'unit.kg': 'kg',
    'product.add': 'Add to basket',
    'product.inBasket': 'In basket',
    'product.about': 'About this product',
    'product.close': 'Close',

    'search.empty': 'Nothing found',
    'search.hint': 'Type the name in any of the three languages — «лосось» and «salmon» both work.',

    'profile.personal': 'Personal information',
    'profile.email': 'Email',
    'profile.dob': 'Date of birth',
    'profile.notSet': 'Not added',
    'profile.edit': 'Edit',
    'profile.settings': 'Settings',
    'profile.account': 'Account',
    'profile.signOutConfirm': 'Sign out of your account?',
    'profile.deleteTitle': 'Delete your account?',
    'profile.deleteHint': 'If an order is on its way, it has to be delivered or cancelled first.',
    'profile.deleted': 'Your account has been deleted.',
    'profile.phonePh': 'Enter your phone number',
  },
}
