// Generated from shared/catalogue.json and shared/delivery.json — do not edit.
//
// Change the source and run `npm run sync` at the repository root. Editing
// this file directly makes the website and the app disagree, which is the
// one thing this arrangement exists to prevent; `npm run check` catches it.

import type { CatalogueResponse } from './api'

/* What the shop looks like before the network has ever answered.
 *
 * The app used to have nothing here: a first run with no signal — on a plane,
 * in a lift, on a new phone in a shop with bad reception — showed an empty
 * catalogue and no way to tell that it was empty for the wrong reason. This is
 * the same bundled copy the website carries, generated from the same file.
 *
 * It is a FALLBACK. The moment /api/catalogue answers, every figure here is
 * replaced and the result cached; an order is priced by the server regardless,
 * so a stale line costs a corrected total rather than a wrong bill.
 *
 * The zone fees are the LOW end of each area's range — the app shows a range
 * from lib/zones.ts where it can, and this field has room for one number only.
 */
export const FALLBACK_CATALOGUE: CatalogueResponse = {
  currency: 'AZN',
  delivery: { open: '10:00', close: '22:00', lead_days: 1, weight_tolerance_percent: 10, code_ttl_minutes: 10 },

  categories: [
  { id: 'smoked', name: { az: 'Hisə verilmiş', ru: 'Копчёности', en: 'Smoked Fish' } },
  { id: 'fresh', name: { az: 'Təzə balıqlar', ru: 'Свежая рыба', en: 'Fresh Fish' } },
  { id: 'seafood', name: { az: 'Dəniz məhsulları', ru: 'Морепродукты', en: 'Seafood' } },
  { id: 'poultry', name: { az: 'Toyuq və ət', ru: 'Мясо и птица', en: 'Poultry & Meat' } },
  { id: 'cheese', name: { az: 'Pendir və süd', ru: 'Сыры и молочное', en: 'Cheese & Dairy' } },
  { id: 'pantry', name: { az: 'Xəmir və şirniyyat', ru: 'Выпечка и сладости', en: 'Pastry & Pantry' } },
  ],

  products: [
  {
    id: 'smoked-salmon', category_id: 'smoked', price_minor: 6500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Hisə verilmiş qızıl balıq', ru: 'Лосось холодного копчения', en: 'Smoked Salmon' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Soyuq üsulla hisə verilmiş qızıl balıq, nazik dilimlənmiş.', ru: 'Атлантический лосось холодного копчения, нарезанный вручную.', en: 'Cold-smoked Atlantic salmon, hand-sliced and ready for the board.' },
  },
  {
    id: 'smoked-beluga', category_id: 'smoked', price_minor: 11000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Hisə verilmiş beluqa', ru: 'Белуга копчёная', en: 'Smoked Beluga' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Xəzər beluqası, bütöv halda yavaş hisə verilmiş. Evin bəzəyi.', ru: 'Каспийская белуга медленного копчения целиком. Гордость прилавка.', en: 'Caspian beluga sturgeon, slow-smoked whole. The house showpiece.' },
  },
  {
    id: 'smoked-dorado', category_id: 'smoked', price_minor: 1500, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Hisə verilmiş dorado', ru: 'Дорадо копчёная', en: 'Smoked Dorado' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Bütöv hisə verilmiş dorado — zərif, az duzlu.', ru: 'Дорадо целиком, копчёная на твёрдых породах дерева — нежная, слабосолёная.', en: 'Sea bream smoked whole over hardwood — delicate, lightly salted.' },
  },
  {
    id: 'smoked-trout', category_id: 'smoked', price_minor: 900, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Hisə verilmiş forel', ru: 'Форель копчёная', en: 'Smoked Trout' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Bütöv hisə verilmiş forel — hər gün üçün sevimli seçim.', ru: 'Форель целиком горячего копчения — ежедневный фаворит коптильни.', en: 'Whole smoked trout — the everyday favourite of the smoke house.' },
  },
  {
    id: 'salmon-steaks', category_id: 'fresh', price_minor: 6000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Qızıl balıq steyki', ru: 'Стейки лосося', en: 'Salmon Steaks' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Sifarişlə kəsilmiş qızıl balıq steyki, buz üzərində çatdırılır.', ru: 'Стейки лосося на кости, режем под заказ, привозим на льду.', en: 'Bone-in salmon steaks cut to order, delivered on ice.' },
  },
  {
    id: 'beluga-steaks', category_id: 'fresh', price_minor: 5500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Beluqa steyki', ru: 'Стейки белуги', en: 'Beluga Steaks' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Qalın nərə balığı steyki — sıx, ətli, qril üçün ideal.', ru: 'Толстые осетровые стейки — плотные, мясистые, созданы для гриля.', en: 'Thick sturgeon steaks — firm, meaty, made for the grill.' },
  },
  {
    id: 'fresh-dorado', category_id: 'fresh', price_minor: 2600, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Təzə dorado', ru: 'Дорадо свежая', en: 'Fresh Dorado' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv dorado, sifarişlə təmizlənir.', ru: 'Дорадо целиком, чистим и потрошим по запросу.', en: 'Whole gilt-head bream, gutted and scaled on request.' },
  },
  {
    id: 'fresh-levrek', category_id: 'fresh', price_minor: 2900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Təzə levrek', ru: 'Сибас свежий', en: 'Fresh Sea Bass' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv levrek — yumşaq dadlı, limonla bişirmək üçün əla.', ru: 'Сибас целиком — мягкий, нежный, отлично запекается с лимоном.', en: 'Whole sea bass — mild, flaky, excellent baked with lemon.' },
  },
  {
    id: 'fresh-forel', category_id: 'fresh', price_minor: 2000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Təzə forel filesi', ru: 'Филе форели', en: 'Fresh Trout Fillet' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Dərili forel filesi, sümüksüz, bişirməyə hazır.', ru: 'Филе форели на коже, без костей, готово к приготовлению.', en: 'Skin-on trout fillets, pin-boned and ready to cook.' },
  },
  {
    id: 'tuna-loin', category_id: 'seafood', price_minor: 5000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Tunes filesi', ru: 'Филе тунца, лоин', en: 'Tuna Loin' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv tunes filesi, tünd qırmızı, sashimi keyfiyyətli.', ru: 'Цельный лоин жёлтопёрого тунца, тёмно-красный, качества сашими.', en: 'Whole yellowfin loin, deep red and sashimi-grade when fresh.' },
  },
  {
    id: 'tuna-frozen', category_id: 'seafood', price_minor: 6800, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dondurulmuş tunes', ru: 'Тунец, порции', en: 'Tuna, Frozen Portions' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Vakuumda dondurulmuş tunes porsiyaları.', ru: 'Порции тунца в вакууме, замороженные прямо в море.', en: 'Vacuum-packed tuna portions, individually frozen at sea.' },
  },
  {
    id: 'atlantic-lobster', category_id: 'seafood', price_minor: 6000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 350, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Atlantik omar', ru: 'Атлантический лобстер', en: 'Atlantic Lobster' },
    unit_label: { az: '350 gr', ru: '350 г', en: '350 gr' },
    description: { az: 'Bütöv bişmiş Kanada omarı, qabığında dondurulmuş.', ru: 'Канадский лобстер целиком, варёный, замороженный в панцире.', en: 'Whole cooked Canadian lobster, frozen in the shell.' },
  },
  {
    id: 'octopus-salgado', category_id: 'seafood', price_minor: 7200, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Salqado osminoq', ru: 'Осьминог Salgado', en: 'Salgado Octopus' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv Atlantik osminoq, təmizlənmiş və qablaşdırılmış.', ru: 'Атлантический осьминог целиком, очищенный и разложенный в лотки.', en: 'Whole Atlantic octopus, cleaned and portioned in trays.' },
  },
  {
    id: 'baby-octopus', category_id: 'seafood', price_minor: 2900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Balaca osminoq', ru: 'Мини-осьминог', en: 'Baby Octopus' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv balaca osminoq, təmizlənmiş və dondurulmuş.', ru: 'Молодой осьминог целиком, очищенный и замороженный. Готовится за минуты.', en: 'Whole baby octopus, cleaned and frozen. Tender in minutes.' },
  },
  {
    id: 'unagi-frozen', category_id: 'seafood', price_minor: 7000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Unaqi — dondurulmuş ilan balığı', ru: 'Унаги, угорь в глазури', en: 'Unagi, Glazed Eel' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Yapon üsulu qrildə bişmiş ilan balığı, kabayaki sousunda.', ru: 'Угорь на гриле по-японски в соусе кабаяки. Разогреть и подавать.', en: 'Japanese-style grilled eel in kabayaki glaze. Heat and serve.' },
  },
  {
    id: 'mussel-meat', category_id: 'seafood', price_minor: 2000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Midyə əti', ru: 'Мясо мидий', en: 'Mussel Meat' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Qabıqdan çıxarılmış midyə əti, dondurulmuş.', ru: 'Очищенное мясо мидий, бланшированное и замороженное россыпью.', en: 'Shelled mussel meat, blanched and frozen loose for easy cooking.' },
  },
  {
    id: 'green-mussels', category_id: 'seafood', price_minor: 3900, currency: 'AZN',
    unit_kind: 'g', unit_qty: 800, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Yaşıl midyə', ru: 'Зелёные мидии, Новая Зеландия', en: 'NZ Greenshell Mussels' },
    unit_label: { az: '800 gr', ru: '800 г', en: '800 g' },
    description: { az: 'Yeni Zelandiya yarım qabıqlı midyəsi — ətli və şirin.', ru: 'Новозеландские мидии на половинке раковины — крупные и сладкие.', en: 'New Zealand half-shell mussels — plump, sweet, restaurant grade.' },
  },
  {
    id: 'black-tiger-shrimp', category_id: 'seafood', price_minor: 5900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Black tiger krevet, başlı', ru: 'Креветки блэк тайгер, с головой', en: 'Black Tiger Prawns, Head-On' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: '8/12 ölçülü başlı black tiger krevet — iri ölçü.', ru: 'Креветки 8/12 с головой и в панцире — крупный калибр.', en: 'Size 8/12 head-on tiger prawns — the big ones, shell-on.' },
  },
  {
    id: 'langoustine', category_id: 'seafood', price_minor: 6200, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Langustin', ru: 'Лангустины', en: 'Langoustine' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv langustin, dənizdə dondurulmuş. Qrildə bişirin.', ru: 'Лангустины целиком, заморожены в море. Гриль на сильном огне.', en: 'Whole langoustines, frozen at sea. Grill hard and fast.' },
  },
  {
    id: 'red-caviar', category_id: 'seafood', price_minor: 6500, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Qırmızı ikra', ru: 'Красная икра', en: 'Red Caviar' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Az duzlu qızıl balıq kürüsü, bağlı qabda. İki ölçüdə.', ru: 'Икра лосося слабого посола в запечатанной банке. Две фасовки.', en: 'Salmon roe, lightly salted, in a sealed tin. Two tin sizes.' },
  },
  {
    id: 'kalmar', category_id: 'seafood', price_minor: 2600, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Kalmar', ru: 'Кольца кальмара', en: 'Squid Rings' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Təmizlənmiş kalmar halqaları, çiy dondurulmuş.', ru: 'Очищенные кольца кальмара, сырые замороженные — жарятся за две минуты.', en: 'Cleaned squid rings, frozen raw — fry from frozen in two minutes.' },
  },
  {
    id: 'seafood-mix', category_id: 'seafood', price_minor: 2600, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dəniz məhsulları qarışığı', ru: 'Морской коктейль', en: 'Seafood Mix' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Krevet, midyə, kalmar və osminoq bir paketdə.', ru: 'Креветки, мидии, кальмар и осьминог в одной маринованной упаковке.', en: 'Shrimp, mussels, squid and octopus in one marinated pack.' },
  },
  {
    id: 'black-mussels', category_id: 'seafood', price_minor: 2000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qara midyə', ru: 'Чёрные мидии', en: 'Black Mussels' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Yarım qabıqlı qara midyə — ağ şərab və sarımsaqla bişirin.', ru: 'Чёрные мидии на половинке раковины — тушить с белым вином и чесноком.', en: 'Half-shell black mussels — steam with white wine and garlic.' },
  },
  {
    id: 'french-chicken', category_id: 'poultry', price_minor: 3000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Fransız toyuğu', ru: 'Французская курица', en: 'French Chicken' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Fransadan sertifikatlı bütöv toyuq.', ru: 'Сертифицированный цыплёнок из Франции, целиком в упаковке.', en: 'Certified Label Rouge poussin from France, whole in the bag.' },
  },
  {
    id: 'kend-colpa-700', category_id: 'poultry', price_minor: 900, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Kənd çolpası, kiçik', ru: 'Деревенский цыплёнок, малый', en: 'Village Poussin, Small' },
    unit_label: { az: '1 əd · 700–800 gr', ru: '1 шт · 700–800 г', en: '1 pc · 700–800 gr' },
    description: { az: 'Kənd çolpası, 700–800 qr. Sarı yağlı, təbii dadlı.', ru: 'Цыплёнок свободного выгула, 700–800 г. Жёлтый жир, настоящий вкус.', en: 'Free-range village chicken, 700–800 gr. Yellow fat, real flavour.' },
  },
  {
    id: 'kend-colpa-800', category_id: 'poultry', price_minor: 1000, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Kənd çolpası, iri', ru: 'Деревенский цыплёнок, крупный', en: 'Village Poussin, Large' },
    unit_label: { az: '1 əd · 800–900 gr', ru: '1 шт · 800–900 г', en: '1 pc · 800–900 gr' },
    description: { az: 'Eyni kənd çolpası, 800–900 qr ölçüdə.', ru: 'Та же деревенская птица, на размер больше — 800–900 г.', en: 'The same village bird, one size up at 800–900 gr.' },
  },
  {
    id: 'peking-duck', category_id: 'poultry', price_minor: 3000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Pekin ördəyi', ru: 'Пекинская утка', en: 'Peking Duck' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv pekin ördəyi, sobaya hazır.', ru: 'Пекинская утка целиком, подготовлена для духовки — корочка гарантирована.', en: 'Whole Peking duck, prepared for the oven — crisp skin guaranteed.' },
  },
  {
    id: 'duck-fillet', category_id: 'poultry', price_minor: 2400, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Ördək filesi', ru: 'Филе утиной грудки', en: 'Duck Breast Fillet' },
    unit_label: { az: '1 paket', ru: '1 упак', en: '1 pack' },
    description: { az: 'Dərili ördək döş filesi, vakuum qablaşdırmada.', ru: 'Утиная грудка магре на коже, в вакууме, по две штуки.', en: 'Skin-on magret duck breast, vacuum-packed in pairs.' },
  },
  {
    id: 'duck-leg', category_id: 'poultry', price_minor: 1900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Ördək budu', ru: 'Утиные ножки', en: 'Duck Legs' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Konfi və ya yavaş bişirmə üçün ördək budu.', ru: 'Утиные ножки для конфи или медленного запекания. На развес.', en: 'Duck legs for confit or slow roasting. Sold by the kilo.' },
  },
  {
    id: 'camembert', category_id: 'cheese', price_minor: 1800, currency: 'AZN',
    unit_kind: 'g', unit_qty: 125, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Kamamber pendiri', ru: 'Камамбер', en: 'Camembert' },
    unit_label: { az: '125 gr', ru: '125 г', en: '125 gr' },
    description: { az: 'Normandiyadan yumşaq inək pendiri. Otaq temperaturunda verin.', ru: 'Мягкий сыр с белой плесенью из Нормандии. Подавать комнатной температуры.', en: 'Soft bloomy-rind cow cheese from Normandy. Serve at room temperature.' },
  },
  {
    id: 'brie', category_id: 'cheese', price_minor: 1800, currency: 'AZN',
    unit_kind: 'g', unit_qty: 125, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Bri pendiri', ru: 'Бри', en: 'Brie' },
    unit_label: { az: '125 gr', ru: '125 г', en: '125 gr' },
    description: { az: 'Ağ qabıqlı, yumşaq və kremvari pendir.', ru: 'Мягкий, сливочный, с белой корочкой. Основа любой сырной тарелки.', en: 'Mild, buttery and creamy under a white rind. A board essential.' },
  },
  {
    id: 'parmigiano-reggiano', category_id: 'cheese', price_minor: 2700, currency: 'AZN',
    unit_kind: 'g', unit_qty: 230, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Parmicano Recano', ru: 'Пармиджано Реджано', en: 'Parmigiano Reggiano' },
    unit_label: { az: '230 gr', ru: '230 г', en: '230 gr' },
    description: { az: 'DOP sertifikatlı, Emiliya-Romanyada yetişdirilmiş bərk pendir.', ru: 'Твёрдый сыр DOP, выдержанный в Эмилии-Романье. Отрезаем от головы.', en: 'DOP hard cheese aged in Emilia-Romagna. Cut from the wheel.' },
  },
  {
    id: 'baby-truffle', category_id: 'cheese', price_minor: 4600, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qara trüflü pendir', ru: 'Гауда с чёрным трюфелем', en: 'Black Truffle Gouda' },
    unit_label: { az: '280 gr', ru: '280 г', en: '280 gr' },
    description: { az: 'Qara trüf əlavəli Hollandiya pendiri. Zəngin ətirli.', ru: 'Голландская молодая гауда с чёрным трюфелем. Глубокий землистый вкус.', en: 'Dutch baby gouda studded with black truffle. Deep and earthy.' },
  },
  {
    id: 'baby-green-pesto', category_id: 'cheese', price_minor: 4300, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Yaşıl pesto pendiri', ru: 'Гауда с зелёным песто', en: 'Green Pesto Gouda' },
    unit_label: { az: '280 gr', ru: '280 г', en: '280 gr' },
    description: { az: 'Reyhan pestosu ilə hazırlanmış pendir — parlaq yaşıl rəngli.', ru: 'Молодая гауда с песто из базилика — ярко-зелёная, травяная.', en: 'Baby gouda blended with basil pesto — bright green, herbaceous.' },
  },
  {
    id: 'grana-padano', category_id: 'cheese', price_minor: 2100, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qrana Padano', ru: 'Грана Падано', en: 'Grana Padano' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Yetişdirilmiş İtalyan pendiri — parmicanodan yumşaqdır.', ru: 'Выдержанный итальянский сыр для тёрки — мягче и нежнее пармезана.', en: 'Aged Italian grating cheese — milder and softer than Parmigiano.' },
  },
  {
    id: 'butter', category_id: 'cheese', price_minor: 2500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Kərə yağı', ru: 'Сливочное масло', en: 'Butter' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Təbii kərə yağı, kiloqramla kəsilir.', ru: 'Сливочное масло брусками, режем на килограммы. Для выпечки и на стол.', en: 'Cultured block butter, cut to the kilo. For baking and the table.' },
  },
  {
    id: 'burrata-truffle', category_id: 'cheese', price_minor: 1500, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Trüflü burrata', ru: 'Буррата с трюфелем', en: 'Truffle Burrata' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'İçi trüflü kremli təzə burrata. Gəldiyi gün yeyin.', ru: 'Свежая буррата с трюфельными сливками внутри. Съесть в день доставки.', en: 'Fresh burrata with a truffled cream centre. Eat the day it lands.' },
  },
  {
    id: 'halloumi', category_id: 'cheese', price_minor: 1000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 250, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Hellim pendiri', ru: 'Халуми', en: 'Halloumi' },
    unit_label: { az: '250 gr', ru: '250 г', en: '250 gr' },
    description: { az: 'Qrildə formasını saxlayan pendir. Duzlu dadlı.', ru: 'Сыр для гриля, держит форму на сковороде. Солёный, поскрипывает.', en: 'Grilling cheese that holds its shape in the pan. Squeaky and salty.' },
  },
  {
    id: 'organic-feta', category_id: 'cheese', price_minor: 900, currency: 'AZN',
    unit_kind: 'g', unit_qty: 250, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Orqanik feta', ru: 'Органическая фета', en: 'Organic Feta' },
    unit_label: { az: '250 gr', ru: '250 г', en: '250 gr' },
    description: { az: 'Duzlu suda saxlanan orqanik feta — salat və xəmir üçün.', ru: 'Органическая фета в рассоле — крошится, кислит, для салатов и выпечки.', en: 'Brined organic feta — crumbly, tangy, for salads and pastry.' },
  },
  {
    id: 'frozen-croissant', category_id: 'pantry', price_minor: 2500, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 10, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Dondurulmuş kruassan', ru: 'Круассаны замороженные', en: 'Frozen Croissants' },
    unit_label: { az: 'min. 10 əd', ru: 'от 10 шт', en: 'min. 10 pcs' },
    description: { az: 'Çiy kərə yağlı kruassan — gecə açılır, səhər bişirilir.', ru: 'Сырые масляные круассаны — расстоять ночью, испечь утром.', en: 'Raw butter croissants — prove overnight, bake in the morning.' },
  },
  {
    id: 'frozen-bagels', category_id: 'pantry', price_minor: 2500, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 10, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dondurulmuş beygel', ru: 'Бейглы замороженные', en: 'Frozen Bagels' },
    unit_label: { az: 'min. 10 əd', ru: 'от 10 шт', en: 'min. 10 pcs' },
    description: { az: 'Yarımbişmiş beygel — sobada tamamlayın.', ru: 'Бейглы полуготовые — доводятся в духовке до правильной корочки.', en: 'Par-baked bagels — finish in the oven for a proper crust.' },
  },
  {
    id: 'tortilla-lavash', category_id: 'pantry', price_minor: 1300, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1.5, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Tortilla lavaş', ru: 'Тортилья лаваш', en: 'Tortilla Lavash' },
    unit_label: { az: '1.5 kg', ru: '1,5 кг', en: '1.5 kg' },
    description: { az: '1.5 kq-lıq paketdə yumşaq buğda lavaşı.', ru: 'Мягкие пшеничные тортильи в упаковке 1,5 кг. Для роллов и шаурмы.', en: 'Soft wheat tortillas in a 1.5 kg catering pack. For wraps and shawarma.' },
  },
  {
    id: 'kitkat-matcha', category_id: 'pantry', price_minor: 1300, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'KitKat matça', ru: 'KitKat матча', en: 'KitKat Matcha' },
    unit_label: { az: '1 paket', ru: '1 упак', en: '1 pack' },
    description: { az: 'Yapon mini KitKat, tünd matça dadında.', ru: 'Японский мини-KitKat с тёмной матчей — горчинка зелёного чая, меньше сахара.', en: 'Japanese mini KitKat in dark matcha — bitter green tea, less sugar.' },
  },
  {
    id: 'kitkat-matcha-latte', category_id: 'pantry', price_minor: 900, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'KitKat matça latte', ru: 'KitKat матча латте', en: 'KitKat Matcha Latte' },
    unit_label: { az: '1 paket', ru: '1 упак', en: '1 pack' },
    description: { az: 'Daha şirin və südlü matça versiyası.', ru: 'Более сладкая и молочная версия матчи из японской линейки.', en: 'Sweeter, milkier matcha edition from the Japanese range.' },
  },
  {
    id: 'kitkat-strawberry', category_id: 'pantry', price_minor: 1300, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'KitKat çiyələk', ru: 'KitKat клубника', en: 'KitKat Strawberry' },
    unit_label: { az: '1 paket', ru: '1 упак', en: '1 pack' },
    description: { az: 'Yapon çiyələkli KitKat — ayrı-ayrı bükülmüş.', ru: 'Японский клубничный KitKat — розовый, фруктовый, в индивидуальной упаковке.', en: 'Japanese strawberry KitKat — pink, fruity, individually wrapped.' },
  },
  {
    id: 'smoked-mackerel-fillet', category_id: 'smoked', price_minor: 3500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Hisə verilmiş skumbriya filesi', ru: 'Скумбрия копчёная, филе', en: 'Smoked Mackerel Fillets' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'İsti hisə verilmiş skumbriya filesi — yağlı, dadlı, salataya və ya bilavasitə yeməyə hazır.', ru: 'Филе скумбрии горячего копчения на коже — жирное, насыщенное, готово к столу или в салаты.', en: 'Hot-smoked mackerel fillets, skin-on — rich, oily, ready to eat or flake into salads.' },
  },
  {
    id: 'smoked-herring', category_id: 'smoked', price_minor: 800, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Hisə verilmiş siyənək', ru: 'Сельдь копчёная', en: 'Smoked Herring' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Bütöv isti hisə verilmiş siyənək — qızılı dərili, zərif ətli.', ru: 'Сельдь горячего копчения целиком — золотистая кожа, нежная мякоть, классика.', en: 'Whole hot-smoked herring — golden skin, tender flesh, a classic Eastern European favourite.' },
  },
  {
    id: 'smoked-mackerel', category_id: 'smoked', price_minor: 1000, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Hisə verilmiş skumbriya', ru: 'Скумбрия копчёная', en: 'Smoked Mackerel' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Bütöv isti hisə verilmiş skumbriya, yağlı və dadlı.', ru: 'Скумбрия горячего копчения целиком — жирная и насыщенная.', en: 'Whole hot-smoked mackerel, oily and full-flavoured.' },
  },
  {
    id: 'escolar', category_id: 'smoked', price_minor: 7000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Eskolar', ru: 'Эсколар', en: 'Escolar' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Yağlı ağ balıq, hisə verilmiş və dilimlənmiş halda.', ru: 'Маслянистая белая рыба, копчёная и нарезанная в готовый лоток.', en: 'Buttery white fish, smoked and sliced into a ready tray.' },
  },
  {
    id: 'salmon-trout-fillet', category_id: 'fresh', price_minor: 2200, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qızılı alabalıq filesi', ru: 'Филе форели лосося', en: 'Salmon Trout Fillet' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Norvec qızılı alabalıq filesi, dərili, omega-3 zəngin. Vakuumda təzə qablaşdırılmış.', ru: 'Филе норвежской форели-лосося на коже, богатое омега-3. Упаковано в вакуум.', en: 'Premium Norwegian salmon trout fillet, skin-on, rich in omega-3. Vacuum-packed fresh.' },
  },
  {
    id: 'sudak', category_id: 'fresh', price_minor: 1900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Sudak', ru: 'Судак', en: 'Pike-Perch' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Ağ ətli, az yağlı çay balığı. Qızartma üçün əladır.', ru: 'Постная речная рыба с чистым белым мясом. Лучше всего на сковороде.', en: 'Lean freshwater fish with clean white flesh. Best pan-fried.' },
  },
  {
    id: 'black-caviar', category_id: 'seafood', price_minor: 15000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 100, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Qara ikra', ru: 'Чёрная икра', en: 'Black Caviar' },
    unit_label: { az: '100 gr', ru: '100 г', en: '100 gr' },
    description: { az: 'Premium nərə balığı qara ikrası, az duzlu — şüşə qabda soyuq verilir.', ru: 'Премиальная чёрная икра осетровых, слабого посола — подаётся охлаждённой в стеклянной банке.', en: 'Premium sturgeon black caviar, lightly salted — served chilled in a glass jar.' },
  },
  {
    id: 'vannamei-shrimp', category_id: 'seafood', price_minor: 3200, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Vannamei krevetlər, soyulmuş', ru: 'Креветки ваннамей очищенные', en: 'Vannamei Shrimp, Peeled' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Dondurulmuş vannamei krevet 16/20, soyulmuş — Meduza, 30% sululuq.', ru: 'Замороженные креветки ваннамей 16/20, очищенные — Meduza, 30% глазури.', en: 'Frozen vannamei shrimp 16/20, peeled and deveined — Meduza brand, 30% glaze.' },
  },
  {
    id: 'crab-sticks', category_id: 'seafood', price_minor: 1100, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Krab çubuqları', ru: 'Крабовые палочки', en: 'Crab Sticks' },
    unit_label: { az: '1 paket', ru: '1 упак', en: '1 pack' },
    description: { az: 'Salat və rulet üçün surimi çubuqları — hazır məhsul.', ru: 'Сурими для салатов и роллов — охлаждённые, готовы к использованию.', en: 'Surimi sticks for salads and rolls — chilled, ready to use.' },
  },
  {
    id: 'anchovy-fillet', category_id: 'seafood', price_minor: 500, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Ançous filesi', ru: 'Филе анчоуса', en: 'Anchovy Fillets' },
    unit_label: { az: '1 paket', ru: '1 упак', en: '1 pack' },
    description: { az: 'Yağda marinadlanmış ançous filesi — duzlu, kəskin dadlı.', ru: 'Маринованное филе анчоуса в масле — солёное, яркое, для антипасти.', en: 'Marinated anchovy fillets in oil — salty, sharp, for antipasti.' },
  },
  {
    id: 'peeled-shrimp', category_id: 'seafood', price_minor: 3500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Təmizlənmiş krevetlər', ru: 'Креветки очищенные', en: 'Peeled Shrimp' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bişmiş, təmizlənmiş krevet — makaron və salatlar üçün.', ru: 'Варёные и очищенные — сразу в пасту или салат.', en: 'Cooked, peeled and deveined — straight into pasta or salad.' },
  },
  {
    id: 'korolevskiy-shrimp', category_id: 'seafood', price_minor: 2900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Korolevskiy krevetlər', ru: 'Королевские креветки в панцире', en: 'King Shrimp, Shell-On' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Qabıqlı çiy korolevskiy krevet — sərfəli seçim.', ru: 'Сырые королевские креветки в панцире, на развес. Лучшая цена в каталоге.', en: 'Raw shell-on king shrimp, sold by the kilo. Best value on the board.' },
  },
  {
    id: 'mozzarella', category_id: 'cheese', price_minor: 1000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 125, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Təzə mozzarella', ru: 'Моцарелла свежая', en: 'Fresh Mozzarella' },
    unit_label: { az: '125 gr', ru: '125 г', en: '125 gr' },
    description: { az: 'Klassik təzə mozzarella topları duzlu suda — yumşaq, südlü, kaprese üçün ideal.', ru: 'Классические шарики свежей моцареллы в рассоле — мягкие, молочные, идеал для Капрезе.', en: 'Classic fresh mozzarella balls in brine — soft, milky and perfect for Caprese.' },
  },
  {
    id: 'burrata-plain', category_id: 'cheese', price_minor: 1200, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Burrata', ru: 'Буррата', en: 'Burrata' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'İçi stracciatella kremli təzə burrata — gəldiyi gün yeyin.', ru: 'Свежая буррата с начинкой из страчателлы — съесть в день доставки.', en: 'Fresh burrata with a stracciatella cream centre — eat the day it arrives.' },
  },
  {
    id: 'labne', category_id: 'cheese', price_minor: 800, currency: 'AZN',
    unit_kind: 'g', unit_qty: 250, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Labne', ru: 'Лябне', en: 'Labne' },
    unit_label: { az: '250 gr', ru: '250 г', en: '250 gr' },
    description: { az: 'Süzülmüş qatıq pendiri — qalın, kremli, turşumtul. Çörəkə yayın və ya zeytun yağıyla verin.', ru: 'Отцеженный йогуртовый сыр — густой, кремовый, с кислинкой. На тост или с оливковым маслом.', en: 'Strained yogurt cheese — thick, creamy and tangy. Spread on toast or serve with olive oil.' },
  },
  {
    id: 'goat-cheese', category_id: 'cheese', price_minor: 3800, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Cavan keçi pendiri', ru: 'Молодой козий сыр', en: 'Young Goat Cheese' },
    unit_label: { az: '280 gr', ru: '280 г', en: '280 gr' },
    description: { az: 'Henri Willig Hollandiya cavan keçi pendiri — yüngül, kremli, vegetarian dostu.', ru: 'Молодой козий сыр Henri Willig из Голландии — мягкий, сливочный, вегетарианский.', en: 'Henri Willig young goat cheese from Holland — mild, creamy, vegetarian-friendly.' },
  },
  {
    id: 'chili-gouda', category_id: 'cheese', price_minor: 4300, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qırmızı bibərli qauda', ru: 'Гауда с красным перцем чили', en: 'Red Chili Pepper Gouda' },
    unit_label: { az: '280 gr', ru: '280 г', en: '280 gr' },
    description: { az: 'Qırmızı bibər əlavəli Henri Willig pendiri — kremli Hollandiya bazasında iti dad.', ru: 'Молодая гауда Henri Willig с красным чили — острая, пикантная, на кремовой голландской основе.', en: 'Henri Willig baby gouda studded with red chilli — bold heat in a creamy Dutch base.' },
  },
  {
    id: 'gran-guardia', category_id: 'cheese', price_minor: 2200, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Gran Quardia', ru: 'Гран Гуардиа', en: 'Gran Guardia' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Ghidetti İtalyan bərk pendiri, Grana üslubunda yetişdirilmiş — qozyemiş dadlı, rendə üçün ideal.', ru: 'Итальянский твёрдый сыр Ghidetti в стиле Грана — ореховый, зернистый, идеален для тёрки.', en: 'Ghidetti Italian hard cheese, aged in the style of Grana — nutty, granular, ideal for grating.' },
  },
  {
    id: 'aged-gouda-333', category_id: 'cheese', price_minor: 2500, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Köhnəlmiş qauda 333', ru: 'Выдержанная гауда 333', en: 'Aged Gouda 333' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Veenmeester qauda, 333 gün yetişdirilmiş — karamel notlu, sıx, tirozin kristalları.', ru: 'Гауда Veenmeester 333 дня выдержки — карамельные ноты, плотная, с кристаллами тирозина.', en: 'Veenmeester Gouda matured 333 days — caramel notes, firm crunch, tyrosine crystals.' },
  },
  {
    id: 'aged-gouda-444', category_id: 'cheese', price_minor: 3000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Köhnəlmiş qauda 444', ru: 'Выдержанная гауда 444', en: 'Aged Gouda 444' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Veenmeester qauda, 444 gün yetişdirilmiş — daha dərin dad, qırmızı şərabla əla.', ru: 'Гауда Veenmeester 444 дня выдержки — более глубокий вкус, больше кристаллов, отлична с красным вином.', en: 'Veenmeester Gouda matured 444 days — deeper flavour, more crystals, excellent with red wine.' },
  },
  {
    id: 'aged-gouda-555', category_id: 'cheese', price_minor: 3500, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Köhnəlmiş qauda 555', ru: 'Выдержанная гауда 555', en: 'Aged Gouda 555' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Veenmeester qauda, 555 gün yetişdirilmiş — intensiv, qozyemiş, karamel dadlı. Flaqman.', ru: 'Гауда Veenmeester 555 дней выдержки — насыщенная, ореховая, почти ириска. Флагман линейки.', en: 'Veenmeester Gouda matured 555 days — intense, nutty, almost toffee-like. The flagship.' },
  },
  {
    id: 'gouda', category_id: 'cheese', price_minor: 1100, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qauda pendiri', ru: 'Гауда', en: 'Gouda' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Yarımbərk Hollandiya pendiri — dilimlənən, əriyən.', ru: 'Полутвёрдая голландская гауда — режется, плавится, на каждый день.', en: 'Semi-hard Dutch gouda — sliceable, melts well, everyday cheese.' },
  },
  {
    id: 'pizza-cheese', category_id: 'cheese', price_minor: 700, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Pizza pendiri', ru: 'Сыр для пиццы, тёртый', en: 'Pizza Cheese, Grated' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Doğranmış pizza pendiri — istilikdə yaxşı uzanır.', ru: 'Готовая тёртая смесь моцареллы, которая правильно тянется.', en: 'Pre-grated mozzarella blend that stretches properly under heat.' },
  },
  {
    id: 'frozen-edamame', category_id: 'pantry', price_minor: 900, currency: 'AZN',
    unit_kind: 'g', unit_qty: 400, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dondurulmuş edamame', ru: 'Эдамаме замороженные', en: 'Frozen Edamame' },
    unit_label: { az: '400 gr', ru: '400 г', en: '400 gr' },
    description: { az: 'Nova duzlu edamame — blanşlanmış, dondurulmuş, dəqiqələr ərzində hazır. Bitki zülalı mənbəyi.', ru: 'Солёный эдамаме Nova в стручках — бланшированный, замороженный, готовится за минуты. Источник растительного белка.', en: 'Nova salted edamame in the pod — blanched, frozen and ready in minutes. A good source of plant protein.' },
  },
  {
    id: 'pesto-sauce', category_id: 'pantry', price_minor: 1100, currency: 'AZN',
    unit_kind: 'g', unit_qty: 180, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Reyhan pestosu', ru: 'Песто из базилика', en: 'Pesto al Basilico' },
    unit_label: { az: '180 gr', ru: '180 г', en: '180 gr' },
    description: { az: 'Ottima İtalyan reyhan pestosu — təzə reyhan, sarımsaq və parmezan ilə.', ru: 'Итальянское песто из базилика Ottima — свежий базилик, чеснок и пармезан. Продукт Италии.', en: 'Ottima Italian basil pesto — Prodotto in Italia, made with fresh basil, garlic and Parmesan.' },
  },
  {
    id: 'sundried-tomatoes', category_id: 'pantry', price_minor: 1000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Yağda qurudulmuş pomidor', ru: 'Вяленые помидоры в масле', en: 'Sundried Tomatoes in Oil' },
    unit_label: { az: '280 gr', ru: '280 г', en: '280 gr' },
    description: { az: 'Ottima İtalyan qurudulmuş pomidoru yağda — 130 q süzülmüş, zəngin dadlı.', ru: 'Вяленые помидоры Ottima в масле — 130 г без масла, интенсивный вкус. Продукт Италии.', en: 'Ottima Italian sundried tomatoes in seed oil — 130 g drained weight, intensely flavoured.' },
  },
  {
    id: 'frozen-asparagus', category_id: 'pantry', price_minor: 1400, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dondurulmuş yaşıl quşqonmaz', ru: 'Спаржа зелёная замороженная', en: 'Frozen Green Asparagus' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Nova üzvi dondurulmuş yaşıl quşqonmaz — IQF, 100% təzə, buxarla və ya tavada hazırlanır.', ru: 'Органическая замороженная зелёная спаржа Nova — IQF, 100% свежая, готовить прямо из морозилки.', en: 'Nova organic frozen green asparagus — IQF spears, 100% fresh, steam or stir-fry straight from frozen.' },
  },
  {
    id: 'dimartino-pasta', category_id: 'pantry', price_minor: 1800, currency: 'AZN',
    unit_kind: 'g', unit_qty: 500, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Di Martino × D&G Pasta', ru: 'Паста Di Martino × D&G', en: 'Di Martino × D&G Pasta' },
    unit_label: { az: '500 gr', ru: '500 г', en: '500 gr' },
    description: { az: 'Pastificio G. Di Martino Dolce & Gabbana xüsusi nəşr — Pasta di Gragnano IGP, bürünc kalıpda. Fusilli, Tortiglioni, Spaghetti, Farfalle, Gnocchi Sardi və Linguine növlərində.', ru: 'Лимитированная серия Pastificio G. Di Martino × Dolce & Gabbana — Pasta di Gragnano IGP, отлита в бронзовой матрице. Фузилли, Тортильони, Спагетти, Фарфалле, Ньокки Сарди и Лингвини.', en: 'Pastificio G. Di Martino Dolce & Gabbana special edition — Pasta di Gragnano IGP, bronze-die cut. Available in Fusilli, Tortiglioni, Spaghetti, Farfalle, Gnocchi Sardi and Linguine.' },
  },
  ],

  zones: [
  { id: 'merkez', name: { az: 'Mərkəz (Sahil, 28 May, İçərişəhər)', ru: 'Центр (Сахил, 28 Мая, Ичеришехер)', en: 'City centre (Sahil, 28 May, Icherisheher)' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'nerimanov', name: { az: 'Nərimanov', ru: 'Нариманов', en: 'Narimanov' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'nesimi', name: { az: 'Nəsimi', ru: 'Насими', en: 'Nasimi' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'xetai', name: { az: 'Xətai', ru: 'Хатаи', en: 'Khatai' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'elmler-akademiyasi', name: { az: 'Elmlər Akademiyası', ru: 'Академия наук', en: 'Academy of Sciences' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'genclik', name: { az: 'Gənclik', ru: 'Гянджлик', en: 'Ganjlik' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'yasamal', name: { az: 'Yasamal', ru: 'Ясамал', en: 'Yasamal' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'ag-seher', name: { az: 'Ağ Şəhər', ru: 'Белый город', en: 'White City' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'bayil', name: { az: 'Bayıl', ru: 'Баилово', en: 'Bayil' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'kesle', name: { az: 'Keşlə', ru: 'Кешля', en: 'Keshla' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'binegedi', name: { az: 'Binəqədi', ru: 'Бинагади', en: 'Binagadi' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'badamdar', name: { az: 'Badamdar', ru: 'Бадамдар', en: 'Badamdar' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'nzs', name: { az: 'NZS', ru: 'НЗС', en: 'NZS' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'dernegul', name: { az: 'Dərnəgül', ru: 'Дарнагюль', en: 'Darnagul' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'hezi-aslanov', name: { az: 'Həzi Aslanov', ru: 'Ази Асланов', en: 'Hazi Aslanov' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'ehmedli', name: { az: 'Əhmədli', ru: 'Ахмедлы', en: 'Ahmadli' }, fee_minor: 700, min_order_minor: 0 },
  { id: '8-ci-km', name: { az: '8-ci km', ru: '8-й км', en: '8th km' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'bilecari', name: { az: 'Biləcəri', ru: 'Биладжари', en: 'Bilajari' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'neftciler', name: { az: 'Neftçilər', ru: 'Нефтчиляр', en: 'Neftchilar' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'sabuncu', name: { az: 'Sabunçu', ru: 'Сабунчу', en: 'Sabunchu' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'xalqlar-dostlugu', name: { az: 'Xalqlar Dostluğu', ru: 'Дружба народов', en: 'Khalglar Dostlugu' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'gunesli', name: { az: 'Günəşli', ru: 'Гюнешли', en: 'Gunashli' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'koroglu-etrafi', name: { az: 'Koroğlu ətrafı', ru: 'Район Кёроглу', en: 'Koroghlu area' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'avtovagzal', name: { az: 'Avtovağzal', ru: 'Автовокзал', en: 'Bus station' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'bakixanov', name: { az: 'Bakıxanov (Razin)', ru: 'Бакиханов (Разин)', en: 'Bakikhanov (Razin)' }, fee_minor: 800, min_order_minor: 0 },
  { id: 'yeni-gunesli', name: { az: 'Yeni Günəşli', ru: 'Новый Гюнешли', en: 'New Gunashli' }, fee_minor: 800, min_order_minor: 0 },
  { id: 'sixov', name: { az: 'Şıxov', ru: 'Шихово', en: 'Shikhov' }, fee_minor: 800, min_order_minor: 0 },
  { id: 'masazir', name: { az: 'Masazır', ru: 'Масазыр', en: 'Masazir' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'sulutepe', name: { az: 'Sulutəpə', ru: 'Сулутепе', en: 'Sulutapa' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'ramana', name: { az: 'Ramana', ru: 'Раманы', en: 'Ramana' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'sederek-lokbatan', name: { az: 'Sədərək / Lökbatan', ru: 'Сядяряк / Локбатан', en: 'Sadarak / Lokbatan' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'zabrat', name: { az: 'Zabrat', ru: 'Забрат', en: 'Zabrat' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'mastaga', name: { az: 'Maştağa', ru: 'Маштага', en: 'Mashtagha' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'hovsan', name: { az: 'Hövsan', ru: 'Гёвсан', en: 'Hovsan' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'mehdiabad', name: { az: 'Mehdiabad', ru: 'Мехдиабад', en: 'Mehdiabad' }, fee_minor: 1200, min_order_minor: 0 },
  { id: 'kurdexani', name: { az: 'Kürdəxanı', ru: 'Кюрдаханы', en: 'Kurdakhani' }, fee_minor: 1200, min_order_minor: 0 },
  { id: 'xirdalan', name: { az: 'Xırdalan', ru: 'Хырдалан', en: 'Khirdalan' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'qaradag', name: { az: 'Qaradağ', ru: 'Гарадаг', en: 'Garadagh' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'pirsagi', name: { az: 'Pirşağı', ru: 'Пиршаги', en: 'Pirshaghi' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'novxani', name: { az: 'Novxanı', ru: 'Новханы', en: 'Novkhani' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'turkan', name: { az: 'Türkan', ru: 'Тюркян', en: 'Turkan' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'qala', name: { az: 'Qala', ru: 'Гала', en: 'Gala' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'sagan', name: { az: 'Şağan', ru: 'Шаган', en: 'Shaghan' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'fatmayi', name: { az: 'Fatmayı', ru: 'Фатмаи', en: 'Fatmayi' }, fee_minor: 1800, min_order_minor: 0 },
  { id: 'buzovna', name: { az: 'Buzovna', ru: 'Бузовна', en: 'Buzovna' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'merdekan', name: { az: 'Mərdəkan', ru: 'Мардакян', en: 'Mardakan' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'bilgeh', name: { az: 'Bilgəh', ru: 'Бильгя', en: 'Bilgah' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'nardaran', name: { az: 'Nardaran', ru: 'Нардаран', en: 'Nardaran' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'goradil', name: { az: 'Goradil', ru: 'Горадиль', en: 'Goradil' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'suvelan', name: { az: 'Şüvəlan', ru: 'Шувелян', en: 'Shuvalan' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'zire', name: { az: 'Zirə', ru: 'Зира', en: 'Zira' }, fee_minor: 2000, min_order_minor: 0 },
  ],
}
