// Generated from shared/catalogue.json and shared/delivery.json — do not edit.
//
// Change the source and run `npm run sync` at the repository root. Editing
// this file directly makes the website and the app disagree, which is the
// one thing this arrangement exists to prevent; `npm run check` catches it.

import type { CatalogueResponse } from './api'

/* What the shop looks like before the network has ever answered.
 *
 * The app used to have nothing here: a first run with no signal — on a plane,
 * in a lift, on a new phone in a shop with bad reception — showed an empty
 * catalogue and no way to tell that it was empty for the wrong reason. This is
 * the same bundled copy the website carries, generated from the same file.
 *
 * It is a FALLBACK. The moment /api/catalogue answers, every figure here is
 * replaced and the result cached; an order is priced by the server regardless,
 * so a stale line costs a corrected total rather than a wrong bill.
 *
 * The zone fees are the LOW end of each area's range — the app shows a range
 * from lib/zones.ts where it can, and this field has room for one number only.
 */
export const FALLBACK_CATALOGUE: CatalogueResponse = {
  currency: 'AZN',
  delivery: { open: '10:00', close: '22:00', lead_days: 1, weight_tolerance_percent: 10, code_ttl_minutes: 10 },

  categories: [
  { id: 'smoked', name: { az: 'Hisə verilmiş', ru: 'Копчёности', en: 'Smoked Fish' } },
  { id: 'fresh', name: { az: 'Təzə balıqlar', ru: 'Свежая рыба', en: 'Fresh Fish' } },
  { id: 'seafood', name: { az: 'Dəniz məhsulları', ru: 'Морепродукты', en: 'Seafood' } },
  { id: 'poultry', name: { az: 'Toyuq və ət', ru: 'Мясо и птица', en: 'Poultry & Meat' } },
  { id: 'cheese', name: { az: 'Pendir və süd', ru: 'Сыры и молочное', en: 'Cheese & Dairy' } },
  { id: 'pantry', name: { az: 'Xəmir və şirniyyat', ru: 'Выпечка и сладости', en: 'Pastry & Pantry' } },
  { id: 'souslar', name: { az: 'Souslar', ru: 'Соусы', en: 'Sauces' } },
  { id: 'diger', name: { az: 'Digər', ru: 'Другие', en: 'Others' } },
  { id: 'avropa-pendirleri', name: { az: 'Avropa Pendirləri', ru: 'Европейские сыры', en: 'European cheese' } },
  { id: 'kuruler', name: { az: 'Kürü', ru: 'Икра', en: 'Caviar' } },
  ],

  products: [
  {
    id: 'smoked-salmon', category_id: 'smoked', price_minor: 6500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Hisə verilmiş Qızıl balıq (Smoked Salmon)', ru: 'Лосось холодного копчения', en: 'Smoked Salmon' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Soyuq üsulla hisə verilmiş Norveç qızıl balıq, nazik dilimlənmiş və ya bütov şəkildə sifarış olunur.\nMinimum Sifariş Miqdarı 300 qr.\nBakida hise verilir.', ru: 'Норвежский лосось холодного копчения; в наличии — нарезанный или целым куском.\nМинимальный заказ: 300 г.\nКопчение: Баку.', en: 'Cold-smoked Norwegian salmon; available sliced ​​or whole.\nMinimum order quantity: 300g.\nSmoked in Baku.' },
  },
  {
    id: 'smoked-beluga', category_id: 'smoked', price_minor: 11000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Hisə verilmiş beluqa', ru: 'Белуга копчёная', en: 'Smoked Beluga' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Soyuq hisə verilmiş beluqa balığı \nBütov ya dilimlınmiş halda təqdim sifariş etmək mumkundur', ru: 'Белуга холодного копчения\nДоступна для заказа целиком или в нарезке.', en: 'Cold-smoked beluga sturgeon\nAvailable to order whole or sliced.' },
  },
  {
    id: 'smoked-dorado', category_id: 'smoked', price_minor: 1500, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Hisə verilmiş dorado', ru: 'Дорадо копчёная', en: 'Smoked Dorado' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Bütöv hisə verilmiş dorado — zərif, az duzlu.', ru: 'Дорадо целиком, копчёная на твёрдых породах дерева — нежная, слабосолёная.', en: 'Sea bream smoked whole over hardwood — delicate, lightly salted.' },
  },
  {
    id: 'smoked-trout', category_id: 'smoked', price_minor: 900, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Hisə verilmiş forel', ru: 'Форель копчёная', en: 'Smoked Trout' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Bütöv hisə verilmiş forel — hər gün üçün sevimli seçim.', ru: 'Форель целиком горячего копчения — ежедневный фаворит коптильни.', en: 'Whole smoked trout — the everyday favourite of the smoke house.' },
  },
  {
    id: 'salmon-steaks', category_id: 'fresh', price_minor: 6000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Norveç Salmon Balığı (Qızıl Balıq)', ru: 'Стейки лосося', en: 'Salmon Steaks' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Yüksək keyfiyyətli Norveç salmon balığı – steyk və antrikot kəsimində təqdim olunur. Zərif dadı və yüksək qida dəyəri ilə seçilir, sağlam və ləzzətli seçimdir.  1 steyk 300-500 qram arası olur.', ru: 'Стейки лосося на кости, режем под заказ, привозим на льду. В 1 кг обычно 2–3 стейка, каждый по 300–500 г.', en: 'Bone-in salmon steaks cut to order, delivered on ice. About 2–3 steaks per kilo, each 300–500 g.' },
  },
  {
    id: 'beluga-steaks', category_id: 'fresh', price_minor: 5500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Beluqa steyki', ru: 'Стейки белуги', en: 'Beluga Steaks' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Qalın nərə balığı steyki — sıx, ətli, qril üçün ideal.', ru: 'Толстые осетровые стейки — плотные, мясистые, созданы для гриля.', en: 'Thick sturgeon steaks — firm, meaty, made for the grill.' },
  },
  {
    id: 'fresh-dorado', category_id: 'fresh', price_minor: 2600, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dorado (Çupra)', ru: 'Дорадо', en: 'Dorado' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv dorado, sifarişlə, təmizlənir.\n1 baliq 400 - 600 və ya 600 - 800 qr olur', ru: 'Дорадо целиком, чистим и потрошим по запросу.\n1 рыба весит либо 400 - 600 гр, либо 600 - 800 гр', en: 'Whole sea bream (dorado), cleaned to order.\nEach fish weighs 400–600 g or 600–800 g.' },
  },
  {
    id: 'fresh-levrek', category_id: 'fresh', price_minor: 2900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Levrek', ru: 'Сибас свежий', en: 'Sea Bass' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv Levrek, sifarişlə, təmizlənir.\n1 baliq 400 - 600 olur.', ru: 'Целый сибас, очищенный по заказу.\nВес каждой рыбы — от 400 до 600 граммов.', en: 'Whole sea bass, cleaned to order.\nEach fish weighs between 400 and 600 grams.' },
  },
  {
    id: 'fresh-forel', category_id: 'fresh', price_minor: 2000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Forel', ru: 'Форель', en: 'Trout' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: '1 ədəd bütöv forel balığı (çəki: 2,5–3,5 kq). İstəyinizə uyğun olaraq file və ya steyk formasında doğranır — balığın bütün hissələri birlikdə göndərilir.', ru: 'Целая форель (вес: 2,5–3,5 кг). Нарезаем на филе или стейки по вашему желанию — отправляем со всеми частями рыбы.', en: 'One whole trout (weight: 2.5–3.5 kg). Cut into fillets or steaks to your preference — every part of the fish ships together.' },
  },
  {
    id: 'atlantic-lobster', category_id: 'seafood', price_minor: 6000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 350, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Atlantik omar', ru: 'Атлантический лобстер', en: 'Atlantic Lobster' },
    unit_label: { az: '350 gr', ru: '350 г', en: '350 gr' },
    description: { az: 'Bütöv bişmiş Kanada omarı, qabığında dondurulmuş.', ru: 'Канадский лобстер целиком, варёный, замороженный в панцире.', en: 'Whole cooked Canadian lobster, frozen in the shell.' },
  },
  {
    id: 'octopus-salgado', category_id: 'seafood', price_minor: 7200, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Salqado osminoq', ru: 'Осьминог Salgado', en: 'Salgado Octopus' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv Atlantik osminoq, təmizlənmiş və qablaşdırılmış.', ru: 'Атлантический осьминог целиком, очищенный и разложенный в лотки.', en: 'Whole Atlantic octopus, cleaned and portioned in trays.' },
  },
  {
    id: 'baby-octopus', category_id: 'seafood', price_minor: 2900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Balaca osminoq', ru: 'Мини-осьминог', en: 'Baby Octopus' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv balaca osminoq, təmizlənmiş və dondurulmuş.', ru: 'Молодой осьминог целиком, очищенный и замороженный. Готовится за минуты.', en: 'Whole baby octopus, cleaned and frozen. Tender in minutes.' },
  },
  {
    id: 'mussel-meat', category_id: 'seafood', price_minor: 2000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Midyə əti', ru: 'Мясо мидий', en: 'Mussel Meat' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Qabıqdan çıxarılmış midyə əti, dondurulmuş.', ru: 'Очищенное мясо мидий, бланшированное и замороженное россыпью.', en: 'Shelled mussel meat, blanched and frozen loose for easy cooking.' },
  },
  {
    id: 'green-mussels', category_id: 'seafood', price_minor: 3900, currency: 'AZN',
    unit_kind: 'g', unit_qty: 800, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Yaşıl midyə', ru: 'Зелёные мидии, Новая Зеландия', en: 'NZ Greenshell Mussels' },
    unit_label: { az: '800 gr', ru: '800 г', en: '800 g' },
    description: { az: 'Yeni Zelandiya yarım qabıqlı midyəsi — ətli və şirin.', ru: 'Новозеландские мидии на половинке раковины — крупные и сладкие.', en: 'New Zealand half-shell mussels — plump, sweet, restaurant grade.' },
  },
  {
    id: 'black-tiger-shrimp', category_id: 'seafood', price_minor: 5900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Black tiger krevet, başlı', ru: 'Креветки блэк тайгер, с головой', en: 'Black Tiger Prawns, Head-On' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: '8/12 ölçülü başlı black tiger krevet — iri ölçü.', ru: 'Креветки 8/12 с головой и в панцире — крупный калибр.', en: 'Size 8/12 head-on tiger prawns — the big ones, shell-on.' },
  },
  {
    id: 'langoustine', category_id: 'seafood', price_minor: 6200, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Langustin', ru: 'Лангустины', en: 'Langoustine' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Bütöv langustin, dənizdə dondurulmuş. Qrildə bişirin.', ru: 'Лангустины целиком, заморожены в море. Гриль на сильном огне.', en: 'Whole langoustines, frozen at sea. Grill hard and fast.' },
  },
  {
    id: 'red-caviar', category_id: 'kuruler', price_minor: 9000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Qırmızı ikra', ru: 'Красная икра', en: 'Red Caviar' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Az duzlu keta balıq kürüsü, şüşə qabda\nRusiya istehsalı\nPremium keyfiyyət', ru: 'Слабосоленая икра кеты в стеклянной банке\nПроизведено в России\nПремиальное качество', en: 'Lightly salted chum salmon roe, in a glass jar\nMade in Russia\nPremium quality' },
  },
  {
    id: 'kalmar', category_id: 'seafood', price_minor: 2600, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Kalmar', ru: 'Кольца кальмара', en: 'Squid Rings' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Təmizlənmiş kalmar halqaları, çiy dondurulmuş.', ru: 'Очищенные кольца кальмара, сырые замороженные — жарятся за две минуты.', en: 'Cleaned squid rings, frozen raw — fry from frozen in two minutes.' },
  },
  {
    id: 'seafood-mix', category_id: 'seafood', price_minor: 2600, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dəniz məhsulları qarışığı', ru: 'Морской коктейль', en: 'Seafood Mix' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Krevet, midyə, kalmar və osminoq bir paketdə.', ru: 'Креветки, мидии, кальмар и осьминог в одной маринованной упаковке.', en: 'Shrimp, mussels, squid and octopus in one marinated pack.' },
  },
  {
    id: 'black-mussels', category_id: 'seafood', price_minor: 2000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qara midyə', ru: 'Чёрные мидии', en: 'Black Mussels' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Yarım qabıqlı qara midyə — ağ şərab və sarımsaqla bişirin.', ru: 'Чёрные мидии на половинке раковины — тушить с белым вином и чесноком.', en: 'Half-shell black mussels — steam with white wine and garlic.' },
  },
  {
    id: 'kend-colpa-700', category_id: 'poultry', price_minor: 900, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Kənd çolpası, kiçik', ru: 'Деревенский цыплёнок, малый', en: 'Village Poussin, Small' },
    unit_label: { az: '1 əd · 700–800 gr', ru: '1 шт · 700–800 г', en: '1 pc · 700–800 gr' },
    description: { az: 'Kənd çolpası, 700–800 qr. Sarı yağlı, təbii dadlı.', ru: 'Цыплёнок свободного выгула, 700–800 г. Жёлтый жир, настоящий вкус.', en: 'Free-range village chicken, 700–800 gr. Yellow fat, real flavour.' },
  },
  {
    id: 'kend-colpa-800', category_id: 'poultry', price_minor: 1000, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Kənd çolpası, iri', ru: 'Деревенский цыплёнок, крупный', en: 'Village Poussin, Large' },
    unit_label: { az: '1 əd · 800–900 gr', ru: '1 шт · 800–900 г', en: '1 pc · 800–900 gr' },
    description: { az: 'Eyni kənd çolpası, 800–900 qr ölçüdə.', ru: 'Та же деревенская птица, на размер больше — 800–900 г.', en: 'The same village bird, one size up at 800–900 gr.' },
  },
  {
    id: 'peking-duck', category_id: 'poultry', price_minor: 3000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Pekin ördəyi', ru: 'Пекинская утка', en: 'Peking Duck' },
    unit_label: { az: '2.3 kg', ru: '2.3 кг', en: '2.3 kg' },
    description: { az: 'Bütöv pekin ördəyi, sobaya hazır.', ru: 'Пекинская утка целиком, подготовлена для духовки — корочка гарантирована.', en: 'Whole Peking duck, prepared for the oven — crisp skin guaranteed.' },
  },
  {
    id: 'duck-fillet', category_id: 'poultry', price_minor: 2400, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Ördək filesi', ru: 'Филе утиной грудки', en: 'Duck Breast Fillet' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Dərili ördək döş filesi, vakuum qablaşdırmada.', ru: 'Утиная грудка магре на коже, в вакууме, по две штуки.', en: 'Skin-on magret duck breast, vacuum-packed in pairs.' },
  },
  {
    id: 'duck-leg', category_id: 'poultry', price_minor: 1900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Ördək budu', ru: 'Утиные ножки', en: 'Duck Legs' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Konfi və ya yavaş bişirmə üçün ördək budu.', ru: 'Утиные ножки для конфи или медленного запекания. На развес.', en: 'Duck legs for confit or slow roasting. Sold by the kilo.' },
  },
  {
    id: 'camembert', category_id: 'avropa-pendirleri', price_minor: 1600, currency: 'AZN',
    unit_kind: 'g', unit_qty: 125, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Kamamber pendiri', ru: 'Камамбер', en: 'Camembert' },
    unit_label: { az: '125 gr', ru: '125 г', en: '125 gr' },
    description: { az: 'Kamaber pendiri 125 qr. Almaniya istehsalı', ru: 'Сыр камамбер, 125 г. Произведено в Германии.', en: 'Camembert cheese, 125g. Made in Germany.' },
  },
  {
    id: 'parmigiano-reggiano', category_id: 'avropa-pendirleri', price_minor: 2700, currency: 'AZN',
    unit_kind: 'g', unit_qty: 230, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Parmezan pendiri', ru: 'Пармиджано Реджано', en: 'Parmigiano Reggiano' },
    unit_label: { az: '250 gr', ru: '250 г', en: '250 gr' },
    description: { az: 'Zanetti firması. İtaliya istehsalı.', ru: 'Компания Zanetti. Сделано в Италии.', en: 'Zanetti company. Made in Italy.' },
  },
  {
    id: 'baby-truffle', category_id: 'avropa-pendirleri', price_minor: 4500, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qara trufel pendir', ru: 'Сыр с Черным Трюфелем', en: 'Black Truffle Baby Cheese' },
    unit_label: { az: '320 gr', ru: '280 г', en: '320 gr' },
    description: { az: 'Henry Willig Baby Black Truffle pendiri.  Hollandi isehsalı', ru: 'Henry Willig сыр с чёрным трюфелем. Произведено в Голландии.', en: 'Henry Willig Baby Black Truffle Cheese. Made in Nederland.' },
  },
  {
    id: 'baby-green-pesto', category_id: 'avropa-pendirleri', price_minor: 4300, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Yaşıl pesto pendiri', ru: 'Гауда с зелёным песто', en: 'Green Pesto Gouda' },
    unit_label: { az: '320 gr', ru: '280 г', en: '280 gr' },
    description: { az: 'Reyhan pestosu ilə hazırlanmış pendir — parlaq yaşıl rəngli.', ru: 'Молодая гауда с песто из базилика — ярко-зелёная, травяная.', en: 'Baby gouda blended with basil pesto — bright green, herbaceous.' },
  },
  {
    id: 'butter', category_id: 'cheese', price_minor: 2500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Kərə yağı', ru: 'Сливочное масло', en: 'Butter' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Təbii kərə yağı, kiloqramla kəsilir.\nSifarış 1 gün əvvəl qəbul olunur\nKonservantsız təbii süddən hazırlanır', ru: 'Натуральное сливочное масло, продается на развес.\nЗаказы принимаются за день.\nИзготовлено из натурального молока, без консервантов.', en: 'Natural butter, sold by the kilogram.\nOrders accepted one day in advance.\nMade from natural milk without preservatives.' },
  },
  {
    id: 'burrata-truffle', category_id: 'cheese', price_minor: 1500, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Buratta Truffle Pendiri', ru: 'Буррата с трюфелем', en: 'Truffle Burrata' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Buratta truffle pendiri 200 qr - 15 azn\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Saxlama müddəti 5-7 gün\n* Konservantsız təbii süddən hazırlanır', ru: 'Сыр буррата с трюфелем.\n* Заказы необходимо оформлять за день, так как сыр производится рано утром.\n* Срок годности: 5–7 дней.\n* Изготовлено из натурального молока без консервантов.', en: 'Truffle Burrata cheese \n* Orders must be placed one day in advance, as the cheese is produced early in the morning.\n* Shelf life: 5–7 days.\n* Made from natural milk without preservatives.' },
  },
  {
    id: 'halloumi', category_id: 'cheese', price_minor: 1000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 250, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Hellim pendiri', ru: 'Халуми', en: 'Halloumi cheese' },
    unit_label: { az: '250 gr', ru: '250 г', en: '250 gr' },
    description: { az: 'Hellim pediri \n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Saxlama müddəti 5-7 gün\n* Konservantsız təbii süddən hazırlanır', ru: 'Сыр халуми \n* Заказы необходимо оформлять за день, так как сыр производится рано утром.\n* Срок хранения: 5–7 дней.\n* Изготовлен из натурального молока без консервантов.', en: 'Grilling cheese that holds its shape in the pan. Squeaky and salty.' },
  },
  {
    id: 'organic-feta', category_id: 'cheese', price_minor: 900, currency: 'AZN',
    unit_kind: 'g', unit_qty: 250, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Feta Pendiri', ru: 'Сыр Фета', en: 'Feta cheese' },
    unit_label: { az: '250 gr', ru: '250 г', en: '250 gr' },
    description: { az: 'Feta pendiri \n\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Konservantsız təbii süddən hazırlanır', ru: 'Сыр фета.\n\n* Заказы необходимо оформлять за день, так как сыр производится рано утром.\n* Изготовлен из натурального молока без консервантов.', en: 'Feta cheese \n\n* Orders must be placed one day in advance, as the cheese is produced early in the morning.\n* Made from natural milk without preservatives.' },
  },
  {
    id: 'frozen-croissant', category_id: 'pantry', price_minor: 2500, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 10, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Dondurulmuş kruassan', ru: 'Круассаны замороженные', en: 'Frozen Croissants' },
    unit_label: { az: 'min. 10 əd', ru: 'от 10 шт', en: 'min. 10 pcs' },
    description: { az: 'Dondurulmuş Kroasanlar\nMin sifariş 10 əd - 25 azn\nYerli istehsal\nSifariş 1 gün əvvəl qəbul olunur', ru: 'Замороженные круассаны\nМинимальный заказ: 10 штук — 25 AZN\nМестное производство\nЗаказы принимаются за 1 день', en: 'Frozen Croissants\nMinimum order: 10 pieces – 25 AZN\nLocally produced\nOrders accepted 1 day in advance' },
  },
  {
    id: 'frozen-bagels', category_id: 'pantry', price_minor: 2500, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 10, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dondurulmuş beygelslər', ru: 'Бейглы замороженные', en: 'Frozen Bagels' },
    unit_label: { az: 'min. 10 əd', ru: 'от 10 шт', en: 'min. 10 pcs' },
    description: { az: 'Dondurulmuş beygel\nMin sifariş 10 əd - 25 azn\nYerli istehsal\nSifariş 1 gün əvvəl qəbul olunur', ru: 'Замороженные бейглы\nМинимальный заказ: 10 штук — 25 AZN\nМестное производство\nЗаказы принимаются за 1 день', en: 'Frozen bagels\nMinimum order: 10 pieces – 25 AZN\nLocally produced\nOrders accepted 1 day in advance' },
  },
  {
    id: 'tortilla-lavash', category_id: 'pantry', price_minor: 1300, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1.5, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Tortilla lavaş', ru: 'Тортилья лаваш', en: 'Tortilla Lavash' },
    unit_label: { az: '0.93 kg', ru: '0.93 кг', en: '0.93 kg' },
    description: { az: '0.93 kq-lıq paketdə yumşaq buğda lavaşı.', ru: 'Мягкие пшеничные тортильи в упаковке 0.93 кг. Для роллов и шаурмы.', en: 'Soft wheat tortillas in a 0.93 kg catering pack. For wraps and shawarma.' },
  },
  {
    id: 'kitkat-strawberry', category_id: 'pantry', price_minor: 1300, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'KitKat çiyələk', ru: 'KitKat клубника', en: 'KitKat Strawberry' },
    unit_label: { az: '1 bağlama', ru: '1 упаковка', en: '1 pack' },
    description: { az: 'Yapon çiyələkli KitKat — ayrı-ayrı bükülmüş.\nBağlamada 10 ədəd balaca kit katlar', ru: 'Японский клубничный KitKat — розовый, фруктовый, в индивидуальной упаковке.\nВ упаковке 10 мини-батончиков KitKat.', en: 'Japanese strawberry KitKat — pink, fruity, individually wrapped.\nThe package contains 10 mini KitKats.' },
  },
  {
    id: 'smoked-mackerel', category_id: 'smoked', price_minor: 1000, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Hisə verilmiş skumbriya', ru: 'Скумбрия копчёная', en: 'Smoked Mackerel' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Bütöv isti hisə verilmiş skumbriya, yağlı və dadlı.', ru: 'Скумбрия горячего копчения целиком — жирная и насыщенная.', en: 'Whole hot-smoked mackerel, oily and full-flavoured.' },
  },
  {
    id: 'escolar', category_id: 'smoked', price_minor: 7000, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Hise verilmiş Eskolar (Maslyanoy)', ru: 'Копченный Эсколар', en: 'Smoked Escolar' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Yağlı ağ balıq, hisə verilmiş və dilimlənmiş halda.', ru: 'Маслянистая белая рыба, копчёная и нарезанная в готовый лоток.', en: 'Buttery white fish, smoked and sliced into a ready tray.' },
  },
  {
    id: 'hise-verilmis-qizil-baliq-flagman-smoked-salmon', category_id: 'smoked', price_minor: 6500, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: true, image: null,
    name: { az: 'Hise verilmiş Qızıl balıq Flagman (Smoked Salmon)', ru: 'Копченный Салмон Flagman', en: 'Smoked salmon Flagman' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Hise verilmiş Norveç qızıl balıq \nFlagman brendi\nStandart 1 kg liq bağlamada\nDondurulmuş və nazik dilimlənmiş.\nUkraina İstehsalı', ru: 'Норвежский лосось холодного копчения\nТорговая марка Flagman\nСтандартная упаковка 1 кг\nЗамороженный, тонкая нарезка.\nСделано в Украине', en: 'Smoked Norwegian salmon\nFlagman brand\nStandard 1 kg package\nFrozen and thinly sliced.' },
  },
  {
    id: 'salmon-trout-fillet', category_id: 'seafood', price_minor: 4500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dondurulmuş Salmon Filesi', ru: 'Замороженное Филе Лосося', en: 'Frozen Salmon Fillet' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Dondurulmuş Norveç qızılı balıq filesi\n2-2.5 kg olur.', ru: 'Замороженное филе норвежского морского лосося\nВес — 2–2,5 кг.', en: 'Frozen Norwegian Salmon fillet\nThey weigh 2–2.5 kg.' },
  },
  {
    id: 'sudak', category_id: 'fresh', price_minor: 1900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Sudak', ru: 'Судак', en: 'Pike-Perch' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Ağ ətli, az yağlı çay balığı. Qızartma üçün əladır.', ru: 'Постная речная рыба с чистым белым мясом. Лучше всего на сковороде.', en: 'Lean freshwater fish with clean white flesh. Best pan-fried.' },
  },
  {
    id: 'black-caviar', category_id: 'seafood', price_minor: 15000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 100, is_weight_based: true, is_popular: true, image: null,
    name: { az: 'Qara ikra', ru: 'Чёрная икра', en: 'Black Caviar' },
    unit_label: { az: '100 gr', ru: '100 г', en: '100 gr' },
    description: { az: 'Premium nərə balığı qara ikrası, az duzlu — şüşə qabda soyuq verilir.', ru: 'Премиальная чёрная икра осетровых, слабого посола — подаётся охлаждённой в стеклянной банке.', en: 'Premium sturgeon black caviar, lightly salted — served chilled in a glass jar.' },
  },
  {
    id: 'crab-sticks', category_id: 'seafood', price_minor: 1100, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Krab çubuqları', ru: 'Крабовые палочки', en: 'Crab Sticks' },
    unit_label: { az: '1 paket', ru: '1 упак', en: '1 pack' },
    description: { az: 'Salat və rulet üçün surimi çubuqları — hazır məhsul.', ru: 'Сурими для салатов и роллов — охлаждённые, готовы к использованию.', en: 'Surimi sticks for salads and rolls — chilled, ready to use.' },
  },
  {
    id: 'anchovy-fillet', category_id: 'seafood', price_minor: 500, currency: 'AZN',
    unit_kind: 'pack', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Ançous filesi', ru: 'Филе анчоуса', en: 'Anchovy Fillets' },
    unit_label: { az: '1 paket', ru: '1 упак', en: '1 pack' },
    description: { az: 'Yağda marinadlanmış ançous filesi — duzlu, kəskin dadlı.', ru: 'Маринованное филе анчоуса в масле — солёное, яркое, для антипасти.', en: 'Marinated anchovy fillets in oil — salty, sharp, for antipasti.' },
  },
  {
    id: 'peeled-shrimp', category_id: 'seafood', price_minor: 3500, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Təmizlənmiş krevetlər', ru: 'Креветки очищенные', en: 'Peeled Shrimp' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Dondurulmuş vanamey krevet, başsız, soyulmuş, quyruqlu, çiy\n16/20', ru: 'Креветки ваннамей замороженные, без головы, очищенные, с хвостиком, сырые\n16/20', en: 'Frozen Vannamei shrimp, headless, peeled, tail-on, raw\n16/20' },
  },
  {
    id: 'korolevskiy-shrimp', category_id: 'seafood', price_minor: 2900, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Korolevskiy krevetlər', ru: 'Королевские креветки в панцире', en: 'King Shrimp, Shell-On' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Qabıqlı çiy korolevskiy krevet — sərfəli seçim.', ru: 'Сырые королевские креветки в панцире, на развес. Лучшая цена в каталоге.', en: 'Raw shell-on king shrimp, sold by the kilo. Best value on the board.' },
  },
  {
    id: 'mozzarella', category_id: 'cheese', price_minor: 1000, currency: 'AZN',
    unit_kind: 'g', unit_qty: 125, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Mozzarella pendiri', ru: 'Моцарелла', en: 'Mozzarella' },
    unit_label: { az: '200 qr', ru: '200 г', en: '200 gr' },
    description: { az: 'Mozzarella pendiri\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Saxlama müddəti 5-7 gün\n* Konservantsız təbii süddən hazırlanır', ru: 'Сыр моцарелла\n* Заказы принимаются за день до доставки, так как сыр производится рано утром\n* Срок годности: 5–7 дней\n* Изготовлен из натурального молока без консервантов', en: 'Mozzarella cheese\n* Orders are accepted one day in advance, as the cheese is produced early in the morning\n* Shelf life: 5–7 days\n* Made from natural milk without preservatives\n* Изготовлен из натурального молока без консервантов' },
  },
  {
    id: 'burrata-plain', category_id: 'cheese', price_minor: 1100, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Burrata pendiri', ru: 'Буррата', en: 'Burrata cheese' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Buratta pendiri\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Saxlama müddəti 5-7 gün\n* Konservantsız təbii süddən hazırlanır', ru: 'Сыр буррата\n* Заказы принимаются за день до доставки, так как сыр производится рано утром\n* Срок годности: 5–7 дней\n* Изготовлен из натурального молока без консервантов', en: 'Burrata cheese\n* Orders are accepted one day in advance, as the cheese is produced early in the morning\n* Shelf life: 5–7 days\n* Made from natural milk without preservatives' },
  },
  {
    id: 'labne', category_id: 'cheese', price_minor: 1200, currency: 'AZN',
    unit_kind: 'g', unit_qty: 250, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Strataçella pendiri', ru: 'Страчателла сыр', en: 'Stracciatella cheese' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Strataçella pendiri\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Saxlama müddəti 5-7 gün\n* Konservantsız təbii süddən hazırlanır', ru: 'Сыр Страчателла\n* Заказы принимаются за день до доставки, так как сыр производится рано утром\n* Срок годности: 5–7 дней\n* Изготовлен из натурального молока без консервантов.', en: 'Stracciatella cheese\n* Orders are accepted one day in advance, as the cheese is produced early in the morning\n* Shelf life: 5–7 days\n* Made from natural milk without preservatives' },
  },
  {
    id: 'goat-cheese', category_id: 'avropa-pendirleri', price_minor: 4500, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Keçi pendiri', ru: 'Козий сыр', en: 'Goat Young Cheese' },
    unit_label: { az: '320 gr', ru: '320 г', en: '320 gr' },
    description: { az: 'Henry Willig Baby Goat Young pendiri.  Hollandi isehsalı', ru: 'Henry Willig Baby Goat Young сыр. Произведено в Голландии', en: 'Henry Willig Baby Goat Young Cheese. Made in Nederland.' },
  },
  {
    id: 'chili-gouda', category_id: 'avropa-pendirleri', price_minor: 4200, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qırmızı bibərli pendir', ru: 'Сыр с красным перцем чили', en: 'Red Chili Pepper Cheese' },
    unit_label: { az: '320 gr', ru: '320 г', en: '320 gr' },
    description: { az: 'Henry Willig Baby Red Chili Peppers pendiri. Hollandiya istehsalı.', ru: 'Henry Willig Baby Red Chili Peppers Сыр. Произведено в Голландии', en: 'Henry Willig Baby Red Chili Peppers Cheese. Made in Nederland.' },
  },
  {
    id: 'aged-gouda-333', category_id: 'avropa-pendirleri', price_minor: 4400, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: '333 Günlük Gauda pendiri (Veenmeester 333)', ru: '333 дней Выдержанная гауда (Veenmeester 333)', en: '333 days Aged Gouda (Veenmeester 333)' },
    unit_label: { az: '300 gr', ru: '300 г', en: '300 gr' },
    description: { az: 'Veenmeester qauda, 333 gün yetişdirilmiş — karamel notlu, sıx, tirozin kristalları.', ru: 'Гауда Veenmeester 333 дня выдержки — карамельные ноты, плотная, с кристаллами тирозина.', en: 'Veenmeester Gouda matured 333 days — caramel notes, firm crunch, tyrosine crystals.' },
  },
  {
    id: 'aged-gouda-444', category_id: 'avropa-pendirleri', price_minor: 4700, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: '444 Günlük Gauda pendiri (Veenmeester 444)', ru: '444 дней Выдержанная гауда', en: '444 days Aged Gouda (Veenmeester 444)' },
    unit_label: { az: '300 gr', ru: '300 г', en: '300 gr' },
    description: { az: 'Veenmeester qauda, 444 gün yetişdirilmiş — daha dərin dad, qırmızı şərabla əla.', ru: 'Гауда Veenmeester 444 дня выдержки — более глубокий вкус, больше кристаллов, отлична с красным вином.', en: 'Veenmeester Gouda matured 444 days — deeper flavour, more crystals, excellent with red wine.' },
  },
  {
    id: 'aged-gouda-555', category_id: 'avropa-pendirleri', price_minor: 4900, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: '555 Günlük Gauda pendiri (Veenmeester 555)', ru: '555 дней Выдержанная гауда', en: '555 days Aged Gouda (Veenmeester 555)' },
    unit_label: { az: '300 gr', ru: '300 г', en: '300 gr' },
    description: { az: 'Veenmeester qauda, 555 gün yetişdirilmiş — intensiv, qozyemiş, karamel dadlı. Flaqman.', ru: 'Гауда Veenmeester 555 дней выдержки — насыщенная, ореховая, почти ириска. Флагман линейки.', en: 'Veenmeester Gouda matured 555 days — intense, nutty, almost toffee-like. The flagship.' },
  },
  {
    id: 'gouda', category_id: 'cheese', price_minor: 1100, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Yerli Qauda pendiri', ru: 'Местная Гауда', en: 'Gouda' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Yarımbərk Hollandiya pendiri — dilimlənən, əriyən.\nYerli Istehsal\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Konservantsız təbii süddən hazırlanır', ru: 'Полутвердый сыр голландского типа — хорошо режется и плавится.\nМестное производство\n* Заказы принимаются за день до доставки, так как сыр изготавливается рано утром.\n* Изготовлен из натурального молока без консервантов.', en: 'Semi-hard Dutch-style cheese — sliceable and meltable.\nLocally produced\n* Orders are accepted one day in advance, as the cheese is produced early in the morning.\n* Made from natural milk without preservatives.' },
  },
  {
    id: 'pizza-cheese', category_id: 'cheese', price_minor: 700, currency: 'AZN',
    unit_kind: 'g', unit_qty: 200, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Pizza pendiri', ru: 'Сыр для пиццы, тёртый', en: 'Pizza Cheese, Grated' },
    unit_label: { az: '200 gr', ru: '200 г', en: '200 gr' },
    description: { az: 'Doğranmış pizza pendiri — istilikdə yaxşı uzanır.\nYerli istehsal\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Konservantsız təbii süddən hazırlanır', ru: 'Тертый сыр для пиццы — хорошо тянется при нагревании.\nМестное производство\n* Заказы принимаются за день до доставки, так как сыр производится рано утром.\n* Изготовлен из натурального молока без консервантов.', en: 'Shredded pizza cheese — stretches well when heated.\nLocally produced\n* Orders are accepted one day in advance, as the cheese is produced early in the morning.\n* Made from natural milk without preservatives.' },
  },
  {
    id: 'mini-mozzarella-pendiri', category_id: 'cheese', price_minor: 1000, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Mini Mozzarella pendiri', ru: 'Мини Моцарелла', en: 'Mini Mozzarella' },
    unit_label: { az: '1 ədəd', ru: '1 шт', en: '1 piece' },
    description: { az: 'Mini Mozzarella pendiri\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Saxlama müddəti 5-7 gün\n* Konservantsız təbii süddən hazırlanır', ru: 'Сыр мини Моцарелла\n* Заказы принимаются за день до доставки, так как сыр производится рано утром\n* Срок годности: 5–7 дней\n* Изготовлен из натурального молока без консервантов', en: 'Mini Mozzarella cheese\n* Orders are accepted one day in advance, as the cheese is produced early in the morning\n* Shelf life: 5–7 days\n* Made from natural milk without preservatives' },
  },
  {
    id: 'suluquni-pendiri', category_id: 'cheese', price_minor: 1800, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Suluquni pendiri', ru: 'Сыр Сулугуни', en: 'Suluquni cheese' },
    unit_label: { az: '500 qr', ru: '500 г', en: '500 qr' },
    description: { az: 'Məhşur Gürcü pendiri Suluquni \nYerli İstehsal\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Konservantsız təbii süddən hazırlanır', ru: 'Знаменитый грузинский сыр сулугуни\nМестное производство\n* Заказы принимаются за день до получения, так как сыр изготавливается рано утром\n* Изготовлен из натурального молока без консервантов', en: 'Famous Georgian Sulguni Cheese\nLocally Produced\n* Orders are accepted one day in advance, as the cheese is produced early in the morning\n* Made from natural milk without preservatives' },
  },
  {
    id: 'rikotta-pendiri', category_id: 'cheese', price_minor: 700, currency: 'AZN',
    unit_kind: 'pc', unit_qty: 1, is_weight_based: false, is_popular: false, image: null,
    name: { az: 'Rikotta Pendiri', ru: 'Сыр Рикотта', en: 'Ricotta cheese' },
    unit_label: { az: '250 qr', ru: '250 г', en: '250 qr' },
    description: { az: 'Yumşaq, kremli teksturaya və zərif dada malik İtalyan pendiri.\n* Yerli istehsal\n* Sifarış 1 gün əvvəl qəbul olunur, çünki pendirlər səhər tezdən istehsal olunur\n* Konservantsız təbii süddən hazırlanır', ru: 'Итальянский сыр с мягкой, сливочной текстурой и нежным вкусом.\n* Местное производство\n* Заказы принимаются за день до доставки, так как сыр изготавливается рано утром\n* Изготовлен из натурального молока без консервантов', en: 'An Italian cheese with a soft, creamy texture and a delicate flavor.\n* Locally produced\n* Orders are accepted one day in advance, as the cheese is produced early in the morning\n* Made from natural milk without preservatives' },
  },
  {
    id: 'frozen-edamame', category_id: 'diger', price_minor: 900, currency: 'AZN',
    unit_kind: 'g', unit_qty: 400, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dondurulmuş edamame', ru: 'Эдамаме замороженные', en: 'Frozen Edamame' },
    unit_label: { az: '400 gr', ru: '400 г', en: '400 gr' },
    description: { az: 'Nova duzlu edamame — blanşlanmış, dondurulmuş, dəqiqələr ərzində hazır. Bitki zülalı mənbəyi.', ru: 'Солёный эдамаме Nova в стручках — бланшированный, замороженный, готовится за минуты. Источник растительного белка.', en: 'Nova salted edamame in the pod — blanched, frozen and ready in minutes. A good source of plant protein.' },
  },
  {
    id: 'pesto-sauce', category_id: 'souslar', price_minor: 900, currency: 'AZN',
    unit_kind: 'g', unit_qty: 180, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Pesto sous', ru: 'Песто из базилика', en: 'Pesto al Basilico' },
    unit_label: { az: '180 gr', ru: '180 г', en: '180 gr' },
    description: { az: 'Ottima İtalyan pesto sousu — təzə reyhan, sarımsaq və parmezan ilə.\nItaliya istehsalı', ru: 'Превосходный итальянский соус песто — со свежим базиликом, чесноком и пармезаном.\nПроизведено в Италии.', en: 'Ottima Italian basil pesto — Prodotto in Italia, made with fresh basil, garlic and Parmesan.' },
  },
  {
    id: 'sundried-tomatoes', category_id: 'diger', price_minor: 1100, currency: 'AZN',
    unit_kind: 'g', unit_qty: 280, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Qurudulmuş pomidor yağda', ru: 'Вяленые помидоры в масле', en: 'Sundried Tomatoes in Oil' },
    unit_label: { az: '280 gr', ru: '280 г', en: '280 gr' },
    description: { az: 'Ottima İtalyan qurudulmuş pomidoru yağda — 280 q süzülmüş, zəngin dadlı.', ru: 'Вяленые помидоры Ottima в масле — 130 г без масла, интенсивный вкус. Продукт Италии.', en: 'Ottima Italian sundried tomatoes in seed oil — 130 g drained weight, intensely flavoured.' },
  },
  {
    id: 'frozen-asparagus', category_id: 'pantry', price_minor: 2200, currency: 'AZN',
    unit_kind: 'kg', unit_qty: 1, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Dondurulmuş Qulancar', ru: 'Спаржа зелёная замороженная', en: 'Frozen Green Asparagus' },
    unit_label: { az: '1 kg', ru: '1 кг', en: '1 kg' },
    description: { az: 'Nova üzvi dondurulmuş yaşıl quşqonmaz — IQF, 100% təzə, buxarla və ya tavada hazırlanır.', ru: 'Органическая замороженная зелёная спаржа Nova — IQF, 100% свежая, готовить прямо из морозилки.', en: 'Nova organic frozen green asparagus — IQF spears, 100% fresh, steam or stir-fry straight from frozen.' },
  },
  {
    id: 'dimartino-pasta', category_id: 'pantry', price_minor: 1800, currency: 'AZN',
    unit_kind: 'g', unit_qty: 500, is_weight_based: true, is_popular: false, image: null,
    name: { az: 'Di Martino × D&G Pasta', ru: 'Паста Di Martino × D&G', en: 'Di Martino × D&G Pasta' },
    unit_label: { az: '500 gr', ru: '500 г', en: '500 gr' },
    description: { az: 'Pastificio G. Di Martino Dolce & Gabbana xüsusi nəşr — Pasta di Gragnano IGP, bürünc kalıpda. Fusilli, Tortiglioni, Spaghetti, Farfalle, Gnocchi Sardi və Linguine növlərində.', ru: 'Лимитированная серия Pastificio G. Di Martino × Dolce & Gabbana — Pasta di Gragnano IGP, отлита в бронзовой матрице. Фузилли, Тортильони, Спагетти, Фарфалле, Ньокки Сарди и Лингвини.', en: 'Pastificio G. Di Martino Dolce & Gabbana special edition — Pasta di Gragnano IGP, bronze-die cut. Available in Fusilli, Tortiglioni, Spaghetti, Farfalle, Gnocchi Sardi and Linguine.' },
  },
  ],

  zones: [
  { id: 'merkez', name: { az: 'Mərkəz (Sahil, 28 May, İçərişəhər)', ru: 'Центр (Сахил, 28 Мая, Ичеришехер)', en: 'City centre (Sahil, 28 May, Icherisheher)' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'nerimanov', name: { az: 'Nərimanov', ru: 'Нариманов', en: 'Narimanov' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'nesimi', name: { az: 'Nəsimi', ru: 'Насими', en: 'Nasimi' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'xetai', name: { az: 'Xətai', ru: 'Хатаи', en: 'Khatai' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'elmler-akademiyasi', name: { az: 'Elmlər Akademiyası', ru: 'Академия наук', en: 'Academy of Sciences' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'genclik', name: { az: 'Gənclik', ru: 'Гянджлик', en: 'Ganjlik' }, fee_minor: 500, min_order_minor: 0 },
  { id: 'yasamal', name: { az: 'Yasamal', ru: 'Ясамал', en: 'Yasamal' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'ag-seher', name: { az: 'Ağ Şəhər', ru: 'Белый город', en: 'White City' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'bayil', name: { az: 'Bayıl', ru: 'Баилово', en: 'Bayil' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'kesle', name: { az: 'Keşlə', ru: 'Кешля', en: 'Keshla' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'binegedi', name: { az: 'Binəqədi', ru: 'Бинагади', en: 'Binagadi' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'badamdar', name: { az: 'Badamdar', ru: 'Бадамдар', en: 'Badamdar' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'nzs', name: { az: 'NZS', ru: 'НЗС', en: 'NZS' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'dernegul', name: { az: 'Dərnəgül', ru: 'Дарнагюль', en: 'Darnagul' }, fee_minor: 600, min_order_minor: 0 },
  { id: 'hezi-aslanov', name: { az: 'Həzi Aslanov', ru: 'Ази Асланов', en: 'Hazi Aslanov' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'ehmedli', name: { az: 'Əhmədli', ru: 'Ахмедлы', en: 'Ahmadli' }, fee_minor: 700, min_order_minor: 0 },
  { id: '8-ci-km', name: { az: '8-ci km', ru: '8-й км', en: '8th km' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'bilecari', name: { az: 'Biləcəri', ru: 'Биладжари', en: 'Bilajari' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'neftciler', name: { az: 'Neftçilər', ru: 'Нефтчиляр', en: 'Neftchilar' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'sabuncu', name: { az: 'Sabunçu', ru: 'Сабунчу', en: 'Sabunchu' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'xalqlar-dostlugu', name: { az: 'Xalqlar Dostluğu', ru: 'Дружба народов', en: 'Khalglar Dostlugu' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'gunesli', name: { az: 'Günəşli', ru: 'Гюнешли', en: 'Gunashli' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'koroglu-etrafi', name: { az: 'Koroğlu ətrafı', ru: 'Район Кёроглу', en: 'Koroghlu area' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'avtovagzal', name: { az: 'Avtovağzal', ru: 'Автовокзал', en: 'Bus station' }, fee_minor: 700, min_order_minor: 0 },
  { id: 'bakixanov', name: { az: 'Bakıxanov (Razin)', ru: 'Бакиханов (Разин)', en: 'Bakikhanov (Razin)' }, fee_minor: 800, min_order_minor: 0 },
  { id: 'yeni-gunesli', name: { az: 'Yeni Günəşli', ru: 'Новый Гюнешли', en: 'New Gunashli' }, fee_minor: 800, min_order_minor: 0 },
  { id: 'sixov', name: { az: 'Şıxov', ru: 'Шихово', en: 'Shikhov' }, fee_minor: 800, min_order_minor: 0 },
  { id: 'masazir', name: { az: 'Masazır', ru: 'Масазыр', en: 'Masazir' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'sulutepe', name: { az: 'Sulutəpə', ru: 'Сулутепе', en: 'Sulutapa' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'ramana', name: { az: 'Ramana', ru: 'Раманы', en: 'Ramana' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'sederek-lokbatan', name: { az: 'Sədərək / Lökbatan', ru: 'Сядяряк / Локбатан', en: 'Sadarak / Lokbatan' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'zabrat', name: { az: 'Zabrat', ru: 'Забрат', en: 'Zabrat' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'mastaga', name: { az: 'Maştağa', ru: 'Маштага', en: 'Mashtagha' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'hovsan', name: { az: 'Hövsan', ru: 'Гёвсан', en: 'Hovsan' }, fee_minor: 1000, min_order_minor: 0 },
  { id: 'mehdiabad', name: { az: 'Mehdiabad', ru: 'Мехдиабад', en: 'Mehdiabad' }, fee_minor: 1200, min_order_minor: 0 },
  { id: 'kurdexani', name: { az: 'Kürdəxanı', ru: 'Кюрдаханы', en: 'Kurdakhani' }, fee_minor: 1200, min_order_minor: 0 },
  { id: 'xirdalan', name: { az: 'Xırdalan', ru: 'Хырдалан', en: 'Khirdalan' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'qaradag', name: { az: 'Qaradağ', ru: 'Гарадаг', en: 'Garadagh' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'pirsagi', name: { az: 'Pirşağı', ru: 'Пиршаги', en: 'Pirshaghi' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'novxani', name: { az: 'Novxanı', ru: 'Новханы', en: 'Novkhani' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'turkan', name: { az: 'Türkan', ru: 'Тюркян', en: 'Turkan' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'qala', name: { az: 'Qala', ru: 'Гала', en: 'Gala' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'sagan', name: { az: 'Şağan', ru: 'Шаган', en: 'Shaghan' }, fee_minor: 1500, min_order_minor: 0 },
  { id: 'fatmayi', name: { az: 'Fatmayı', ru: 'Фатмаи', en: 'Fatmayi' }, fee_minor: 1800, min_order_minor: 0 },
  { id: 'buzovna', name: { az: 'Buzovna', ru: 'Бузовна', en: 'Buzovna' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'merdekan', name: { az: 'Mərdəkan', ru: 'Мардакян', en: 'Mardakan' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'bilgeh', name: { az: 'Bilgəh', ru: 'Бильгя', en: 'Bilgah' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'nardaran', name: { az: 'Nardaran', ru: 'Нардаран', en: 'Nardaran' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'goradil', name: { az: 'Goradil', ru: 'Горадиль', en: 'Goradil' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'suvelan', name: { az: 'Şüvəlan', ru: 'Шувелян', en: 'Shuvalan' }, fee_minor: 2000, min_order_minor: 0 },
  { id: 'zire', name: { az: 'Zirə', ru: 'Зира', en: 'Zira' }, fee_minor: 2000, min_order_minor: 0 },
  ],
}
